/**
 * Catálogo de fontes — entradas (fonte de verdade, ver types.ts).
 *
 * Consolidado do v1 (rotas uni-*, uniConnectors, discoverCore, lojas) e do
 * núcleo v3 (serpapi/suggest/audit). Cada linha reflete o código REAL:
 * recurso, parâmetros e campos devolvidos por cada coletor.
 */
import type { SourceCatalogEntry } from "./types.js";

export const SOURCE_CATALOG: SourceCatalogEntry[] = [
  /* ------------------------------------------------------------ uni --- */
  {
    id: "suggest",
    label: "Google Suggest (autocomplete)",
    group: "uni",
    category: "Tendências",
    method: "api",
    auth: "none",
    capabilities: ["trends", "custom"],
    params: ["query", "lang", "gl", "ds", "limit"],
    data: ["text", "relevance", "seed"],
    resource: "https://suggestqueries.google.com/complete/search?client=chrome&q=&gl=&hl=&ds=",
    status: "implemented",
    tosNote: "Autocomplete público; expansion seeds a-z/0-9; verticais via ds ('' web, yt, n, sh).",
    notes: "Testado no v1: 6 itens reais por termo (demo 'nubank').",
  },
  {
    id: "suggest-provider",
    label: "Autocomplete multi-provedor",
    group: "uni",
    category: "Tendências",
    method: "scrape",
    auth: "none",
    capabilities: ["trends", "custom"],
    params: ["provider", "query", "limit", "lang"],
    data: ["text", "relevance"],
    resource: "autocomplete público: bing/duckduckgo/brave/yahoo/yandex/baidu/naver/amazon/ebay/wikipedia (engine = provedor)",
    status: "implemented",
    tosNote: "10 provedores públicos sem chave; falha de um provedor vira erro honesto. Brave/yahoo podem rate-limitar datacenter.",
    notes: "Bloqueados/nao implementados: tiktok, pinterest, twitch, soundcloud, spotify, walmart/alibaba, apple/play, instagram/x, tenor.",
  },
  {
    id: "trends",
    label: "Google Trends (explore)",
    group: "uni",
    category: "Tendências",
    method: "api",
    auth: "none",
    capabilities: ["trends"],
    params: ["terms", "region", "lang", "timeframe", "gprop", "limit"],
    data: ["timeseries", "geo_ranking", "related_searches"],
    resource: "https://trends.google.com/trends/api/explore + widgetdata/multiline|comparedgeo|relatedsearches",
    status: "implemented",
    tosNote: "3 visoes (timeseries/geo/related); mesma tecnica do pytrends; cookie CONSENT; cache 30min p/ mitigar 429. IP de datacenter pode receber 429/500 (anti-bot do Google) - erro honesto.",
  },
  {
    id: "trending",
    label: "Google Trends Em alta",
    group: "uni",
    category: "Tendências",
    method: "api",
    auth: "none",
    capabilities: ["trends", "news"],
    params: ["geo", "hours", "limit"],
    data: ["title", "traffic", "link", "news_items", "geo", "hours"],
    resource: "https://trends.google.com/trending/rpc?rpcids=i0OFE (batchexecute) + /trending/rss",
    status: "implemented",
    tosNote: "Horas 4/24/48/168 (4h~25, 24h~230, 48h~630, 168h~1800 itens). RSS so top-10.",
  },
  {
    id: "serp",
    label: "SERP multi-engine",
    group: "uni",
    category: "Busca",
    method: "scrape",
    auth: "byok",
    capabilities: ["search"],
    params: ["query", "engine", "limit", "action"],
    data: ["rank", "title", "link", "snippet"],
    resource: "scraping bing/ddg + API brave/google-cse",
    keys: ["BRAVE_API_KEY", "GOOGLE_API_KEY", "GOOGLE_CX"],
    status: "implemented",
    tosNote: "bing/ddg sem chave; Brave e Google CSE exigem chave BYOK (env). DDG rate-limita datacenter; falha de uma engine nao derruba as demais.",
  },
  {
    id: "youtube",
    label: "YouTube",
    group: "uni",
    category: "Mídia",
    method: "scrape",
    auth: "none",
    capabilities: ["media", "social"],
    params: ["query", "action", "limit", "order", "videoId"],
    data: ["videoId", "title", "channel", "published", "views", "duration", "link", "thumb"],
    resource: "scraping ytInitialData (/results) + youtubei/v1/next (comentarios)",
    keys: ["YOUTUBE_API_KEY"],
    status: "implemented",
    tosNote: "Sem chave = scraping; ORDEM relevance/date/views/rating via engine; comments best-effort (pode falhar com erro honesto).",
  },
  {
    id: "reddit",
    label: "Reddit",
    group: "uni",
    category: "Social",
    method: "api",
    auth: "oauth",
    capabilities: ["social"],
    params: ["query", "action", "subreddit", "limit"],
    data: ["title", "url", "author", "score", "subreddit", "numComments", "created", "text"],
    resource: "https://reddit.com/r/… + OAuth client_credentials -> oauth.reddit.com",
    keys: ["REDDIT_CLIENT_ID", "REDDIT_CLIENT_SECRET"],
    status: "implemented",
    tosNote: "JSON publico falha em datacenter (403); OAuth robusto.",
  },
  {
    id: "hackernews",
    label: "Hacker News",
    group: "uni",
    category: "Social",
    method: "api",
    auth: "none",
    capabilities: ["news", "social"],
    params: ["query", "action", "by", "sort", "limit"],
    data: ["id", "title", "url", "author", "points", "numComments", "text", "createdAt"],
    resource: "https://hn.algolia.com/api/v1/search(_by_date) + /items/{id}",
    status: "implemented",
    tosNote: "Arvore de comentarios achatada; testado no v1 (6 itens demo).",
  },
  {
    id: "gdelt",
    label: "GDELT (notícias globais)",
    group: "uni",
    category: "Notícias",
    method: "api",
    auth: "none",
    capabilities: ["news"],
    params: ["query", "sort", "lang", "limit", "startDate", "endDate"],
    data: ["url", "title", "seendate", "sourceCountry", "tone", "sourceLang"],
    resource: "https://api.gdeltproject.org/api/v2/doc/doc?format=json",
    status: "implemented",
    tosNote: "Lang via LANG_MAP (pt/en/es/fr/de/it); campo seendate.",
  },
  {
    id: "arxiv",
    label: "arXiv",
    group: "uni",
    category: "Acadêmico",
    method: "api",
    auth: "none",
    capabilities: ["academic"],
    params: ["query", "limit", "sortBy"],
    data: ["id", "title", "summary", "authors", "published", "updated", "url", "pdf", "categories"],
    resource: "https://export.arxiv.org/api/query?search_query=all:",
    status: "implemented",
    tosNote: "XML atom parseado; paginacao start/max_results. Testado no v1 (3 itens demo).",
  },
  {
    id: "stackexchange",
    label: "StackExchange",
    group: "uni",
    category: "Acadêmico",
    method: "api",
    auth: "none",
    capabilities: ["academic"],
    params: ["query", "site", "limit", "sort"],
    data: ["id", "title", "link", "score", "answerCount", "viewCount", "isAnswered", "body", "createdAt", "tags", "author"],
    resource: "https://api.stackexchange.com/2.3/search/advanced + /questions/{id}/answers",
    status: "implemented",
    tosNote: "Sites: SO, pt.stackoverflow, superuser, serverfault, android, apple, webapps. Testado (6 itens demo).",
  },
  {
    id: "github",
    label: "GitHub (Search API)",
    group: "uni",
    category: "Código",
    method: "api",
    auth: "byok",
    capabilities: ["code"],
    params: ["query", "action", "limit", "sort", "lang", "qualifiers"],
    data: ["name", "description", "url", "stars", "forks", "openIssues", "language", "updatedAt", "topics"],
    resource: "https://api.github.com/search/repositories + /search/issues",
    keys: ["GITHUB_TOKEN"],
    status: "implemented",
    tosNote: "Sem token 10 req/min, com token 30 req/min; erro honesto com reset. Testado (6 itens demo).",
  },
  {
    id: "semanticscholar",
    label: "Semantic Scholar",
    group: "uni",
    category: "Acadêmico",
    method: "api",
    auth: "none",
    capabilities: ["academic"],
    params: ["query", "limit", "sort"],
    data: ["paperId", "title", "abstract", "year", "url", "citationCount", "authors"],
    resource: "https://api.semanticscholar.org/graph/v1/paper/search",
    status: "implemented",
    tosNote: "Backoff exponencial em 429 (5 tentativas, timeout 30s).",
  },
  {
    id: "steam",
    label: "Steam",
    group: "uni",
    category: "Mídia",
    method: "api",
    auth: "none",
    capabilities: ["media"],
    params: ["query", "country", "limit"],
    data: ["name", "price", "appid", "score", "platforms", "metacritic"],
    resource: "https://store.steampowered.com/api/storesearch/?term= (busca real; reviews ainda em ponte)",
    status: "implemented",
    tosNote: "Busca via StoreSearch API (sem chave; cc default br). Reviews (appreviews JSON) seguem como ponte do v1.",
  },
  {
    id: "reclameaqui",
    label: "ReclameAqui",
    group: "uni",
    category: "Reviews",
    method: "api",
    auth: "none",
    capabilities: ["reviews"],
    params: ["query", "action", "company", "limit"],
    data: ["company", "complaint", "status", "date", "title", "text"],
    resource: "https://iosearch.reclameaqui.com.br/raichu-io-site-search-v1/...",
    status: "implemented",
    tosNote: "Cloudflare pode bloquear TLS do Node (datacenter) -> erro honesto com orientacao (curl_cffi/rede). Status derivado: Replica/Resolvido/Nao resolvido/Respondido/Nao respondido.",
  },
  {
    id: "producthunt",
    label: "Product Hunt",
    group: "uni",
    category: "Mídia",
    method: "feed",
    auth: "byok",
    capabilities: ["media", "news"],
    params: ["query", "action", "category", "limit"],
    data: ["id", "name", "tagline", "url", "date", "rank", "votesCount", "commentsCount", "topics"],
    resource: "https://www.producthunt.com/feed (+?category=) e GraphQL v2",
    keys: ["PRODUCT_HUNT_TOKEN"],
    status: "implemented",
    tosNote: "Feed publico (~50 lancamentos/30min TTL cache); GraphQL v2 com token enriquece votes/comments/topics. Testado (6 itens demo).",
  },
  {
    id: "web",
    label: "Web universal (extrator)",
    group: "uni",
    category: "Busca",
    method: "other",
    auth: "none",
    capabilities: ["search", "custom"],
    params: ["action", "url", "content", "limit"],
    data: ["title", "text", "links", "feed_items", "meta"],
    resource: "fetch + extractArticle (regex Readability-like) + parseFeed + splitTextItems",
    status: "implemented",
    tosNote: "25MB limit; timeout 30s; MAX_TEXT_CHARS 20000; MAX_FEED_ITEMS 100. Necessita URL/texto. PDF fora do escopo nativo (erro honesto).",
  },

  /* ------------------------------------------------------ connectors --- */
  {
    id: "itchio",
    label: "itch.io",
    group: "connectors",
    category: "Jogos",
    method: "scrape",
    auth: "none",
    capabilities: ["media"],
    params: ["query", "limit"],
    data: ["title", "url", "price", "description"],
    resource: "scraping https://itch.io/search",
    status: "implemented",
    tosNote: "Busca de jogos indie; scrape HTML.",
  },
  {
id: "devto",
    label: "DEV Community",
    group: "connectors",
    category: "Código",
    method: "api",
    auth: "none",
    capabilities: ["news", "code"],
    params: ["query", "limit"],
    data: ["title", "url", "author", "reactions_count", "comments_count", "tags", "published"],
    resource: "https://dev.to/api/articles (por tag — sem busca full-text pública)",
    status: "implemented",
    tosNote: "Forem API pública por tag (query vira tag); per_page<=30.",
  },
  {
    id: "lobsters",
    label: "Lobsters",
    group: "connectors",
    category: "Social",
    method: "api",
    auth: "none",
    capabilities: ["news", "social"],
    params: ["query", "limit"],
    data: ["title", "url", "author", "score", "comments_count"],
    resource: "https://lobste.rs/t/{tag}.json | /newest.json",
    status: "implemented",
    tosNote: "Busca full-text exige login; v4 usa timeline da tag (query) ou /newest (vazio).",
  },
  {
    id: "mastodon",
    label: "Mastodon",
    group: "connectors",
    category: "Social",
    method: "api",
    auth: "none",
    capabilities: ["social"],
    params: ["query", "hashtag", "limit"],
    data: ["id", "content", "author", "favourites", "reblogs", "created", "url"],
    resource: "https://mastodon.social/api/v1/timelines/tag/{tag} (busca real portada; /api/v2/search precisa de token)",
    status: "implemented",
    tosNote: "Hashtag pública sem auth; query '#termo' ou termo direto.",
  },
  {
    id: "bluesky",
    label: "Bluesky",
    group: "connectors",
    category: "Social",
    method: "api",
    auth: "none",
    capabilities: ["social"],
    params: ["query", "limit"],
    data: ["uri", "text", "author", "likes", "reposts", "created", "url"],
    resource: "https://public.api.bsky.app/xrpc/app.bsky.feed.searchPosts",
    status: "implemented",
    tosNote: "Em datacenters pode responder 403 por IP (verificado ao vivo); comportamento honesto.",
  },
  {
    id: "wikidata",
    label: "Wikidata",
    group: "connectors",
    category: "Conhecimento",
    method: "api",
    auth: "none",
    capabilities: ["custom"],
    params: ["query", "limit"],
    data: ["entityId", "label", "description", "claims", "url"],
    resource: "https://www.wikidata.org/w/api.php (wbsearchentities)",
    lookup: true,
    status: "implemented",
    tosNote: "Busca pública sem chave; entidades com rótulo/descrição/id.",
  },
  {
    id: "openalex",
    label: "OpenAlex",
    group: "connectors",
    category: "Acadêmico",
    method: "api",
    auth: "none",
    capabilities: ["academic"],
    params: ["query", "limit"],
    data: ["id", "title", "doi", "authors", "year", "cited_by_count", "open_access"],
    resource: "https://api.openalex.org/works",
    status: "implemented",
    tosNote: "Busca pública sem chave; papers com doi, autores, citações.",
  },
  {
    id: "crossref",
    label: "Crossref",
    group: "connectors",
    category: "Acadêmico",
    method: "api",
    auth: "none",
    capabilities: ["academic"],
    params: ["query", "limit"],
    data: ["doi", "title", "authors", "year", "journal", "citation_count"],
    resource: "https://api.crossref.org/works",
    status: "implemented",
    tosNote: "Busca bibliográfica pública sem chave (rows<=25).",
  },
  {
    id: "openlibrary",
    label: "Open Library",
    group: "connectors",
    category: "Conhecimento",
    method: "api",
    auth: "none",
    capabilities: ["custom"],
    params: ["query", "limit"],
    data: ["title", "author", "year", "isbn", "cover", "url"],
    resource: "https://openlibrary.org/search.json",
    status: "implemented",
    tosNote: "Busca pública sem chave (limit<=25).",
  },
  {
    id: "npm",
    label: "npm",
    group: "connectors",
    category: "Código",
    method: "api",
    auth: "none",
    capabilities: ["code"],
    params: ["query", "limit"],
    data: ["name", "version", "description", "score", "downloads", "url"],
    resource: "https://registry.npmjs.org/-/v1/search?text=",
    lookup: true,
    status: "implemented",
    tosNote: "Busca pública sem chave (size<=20).",
  },
  {
    id: "pypi",
    label: "PyPI",
    group: "connectors",
    category: "Código",
    method: "api",
    auth: "none",
    capabilities: ["code"],
    params: ["query", "limit"],
    data: ["name", "version", "summary", "author", "license", "url"],
    resource: "https://pypi.org/pypi/{name}/json",
    lookup: true,
    status: "implemented",
  },
  {
    id: "rubygems",
    label: "RubyGems",
    group: "connectors",
    category: "Código",
    method: "api",
    auth: "none",
    capabilities: ["code"],
    params: ["query", "limit"],
    data: ["name", "version", "info", "downloads", "authors", "url"],
    resource: "https://rubygems.org/api/v1/search.json",
    status: "implemented",
  },
  {
    id: "cratesio",
    label: "crates.io",
    group: "connectors",
    category: "Código",
    method: "api",
    auth: "none",
    capabilities: ["code"],
    params: ["query", "limit"],
    data: ["name", "version", "description", "downloads", "recent_downloads", "url"],
    resource: "https://crates.io/api/v1/crates?q=",
    status: "implemented",
  },
  {
    id: "doaj",
    label: "DOAJ (open access)",
    group: "connectors",
    category: "Acadêmico",
    method: "api",
    auth: "none",
    capabilities: ["academic"],
    params: ["query", "limit"],
    data: ["title", "doi", "journal", "authors", "year", "url"],
    resource: "https://doaj.org/api/search/articles/{query}",
    status: "implemented",
  },
  {
    id: "openfoodfacts",
    label: "Open Food Facts",
    group: "connectors",
    category: "Productos",
    method: "api",
    auth: "none",
    capabilities: ["custom"],
    params: ["query", "limit"],
    data: ["code", "name", "brands", "nutriscore", "nova", "categories", "url"],
    resource: "https://world.openfoodfacts.org/cgi/search.pl?search_terms=&search_simple=1&action=process&json=1",
    status: "implemented",
  },
  {
    id: "archive",
    label: "Internet Archive",
    group: "connectors",
    category: "Mídia",
    method: "api",
    auth: "none",
    capabilities: ["media"],
    params: ["query", "type", "limit"],
    data: ["identifier", "title", "creator", "date", "downloads", "type", "url"],
    resource: "https://archive.org/advancedsearch.php",
    status: "implemented",
  },
  {
    id: "tvmaze",
    label: "TVMaze",
    group: "connectors",
    category: "Mídia",
    method: "api",
    auth: "none",
    capabilities: ["media"],
    params: ["query", "limit"],
    data: ["id", "name", "genres", "rating", "premiered", "status", "url", "summary"],
    resource: "https://api.tvmaze.com/search/shows?q=",
    status: "implemented",
  },

  /* -------------------------------------------------------- discover ----- */
  {
    id: "wikitop",
    label: "Wikipedia top views",
    group: "discover",
    category: "Tendências",
    method: "api",
    auth: "none",
    capabilities: ["trends"],
    params: ["project", "date", "limit"],
    data: ["title", "view_count", "rank"],
    resource: "https://wikimedia.org/api/rest_v1/metrics/pageviews/top/{project}/all-access/",
    status: "implemented",
  },
  {
    id: "wikiviews",
    label: "Wikipedia views por artigo",
    group: "discover",
    category: "Tendências",
    method: "api",
    auth: "none",
    capabilities: ["trends"],
    params: ["project", "title", "days", "limit"],
    data: ["title", "daily_views", "total"],
    resource: "https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/...",
    status: "implemented",
  },
  {
    id: "onthisday",
    label: "Wikipedia on this day",
    group: "discover",
    category: "Conhecimento",
    method: "api",
    auth: "none",
    capabilities: ["custom"],
    params: ["lang", "type", "limit"],
    data: ["type", "text", "year", "pages"],
    resource: "https://api.wikimedia.org/feed/v1/wikipedia/{lang}/onthisday/{type}/{mm}/{dd}",
    status: "implemented",
  },
  {
    id: "googlenews",
    label: "Google News RSS",
    group: "discover",
    category: "Notícias",
    method: "feed",
    auth: "none",
    capabilities: ["news"],
    params: ["query", "hl", "gl", "limit"],
    data: ["title", "source", "published", "url"],
    resource: "https://news.google.com/rss/search?q=&hl=&gl=",
    status: "implemented",
    tosNote: "Parse RSS/XML, limit 50; locale fixa pt-BR por ora.",
  },
  {
    id: "podcasts",
    label: "Apple Podcasts (charts)",
    group: "discover",
    category: "Mídia",
    method: "feed",
    auth: "none",
    capabilities: ["media"],
    params: ["country", "limit"],
    data: ["title", "artist", "feed", "artwork", "rank"],
    resource: "https://itunes.apple.com/{cc}/rss/toppodcasts/limit=",
    aliases: ["apple-podcasts", "discover-podcasts"],
    status: "implemented",
  },
  {
    id: "crypto",
    label: "CoinGecko (crypto)",
    group: "discover",
    category: "Tendências",
    method: "api",
    auth: "none",
    capabilities: ["trends"],
    params: ["limit"],
    data: ["name", "symbol", "price", "rank", "change"],
    resource: "https://api.coingecko.com/api/v3/search/trending",
    aliases: ["coingecko", "discover-crypto"],
    status: "implemented",
  },
  {
    id: "steamtop",
    label: "SteamSpy (top jogos)",
    group: "discover",
    category: "Mídia",
    method: "api",
    auth: "none",
    capabilities: ["media", "trends"],
    params: ["request", "limit"],
    data: ["name", "appid", "owners", "players", "price", "score"],
    resource: "https://steamspy.com/api.php?request=top100in2weeks",
    status: "implemented",
    tosNote: "Rate-limit 1 req/s.",
  },
  {
    id: "weather",
    label: "Open-Meteo (clima)",
    group: "discover",
    category: "Dados",
    method: "api",
    auth: "none",
    capabilities: ["custom"],
    params: ["cities", "limit"],
    data: ["city", "temperature", "humidity", "precipitation", "wind", "weathercode"],
    resource: "https://api.open-meteo.com/v1/forecast (lat/lon batch)",
    aliases: ["open-meteo", "discover-clima"],
    status: "implemented",
  },
  {
    id: "brasilapi-feriados",
    label: "Brasil API (feriados)",
    group: "discover",
    category: "Dados",
    method: "api",
    auth: "none",
    capabilities: ["custom"],
    params: ["year", "limit"],
    data: ["date", "name", "type"],
    resource: "https://brasilapi.com.br/api/feriados/v1/{year}",
    aliases: ["brasil", "discover-brasil"],
    status: "implemented",
  },
  {
    id: "brasilapi-taxas",
    label: "Brasil API (taxas)",
    group: "discover",
    category: "Dados",
    method: "api",
    auth: "none",
    capabilities: ["custom"],
    params: ["limit"],
    data: ["nome", "valor", "data"],
    resource: "https://brasilapi.com.br/api/taxas/v1",
    status: "implemented",
  },
  {
    id: "frankfurter",
    label: "Frankfurter (câmbio)",
    group: "discover",
    category: "Dados",
    method: "api",
    auth: "none",
    capabilities: ["custom"],
    params: ["base", "symbols", "limit"],
    data: ["date", "base", "rates"],
    resource: "https://api.frankfurter.dev/v1/latest?base=&symbols=",
    status: "implemented",
  },
  {
    id: "ibge-nomes",
    label: "IBGE (ranking de nomes)",
    group: "discover",
    category: "Dados",
    method: "api",
    auth: "none",
    capabilities: ["custom"],
    params: ["limit"],
    data: ["nome", "frequencia", "rank"],
    resource: "https://servicodados.ibge.gov.br/api/v2/censos/nomes/ranking",
    status: "implemented",
  },
  {
    id: "deezer",
    label: "Deezer",
    group: "discover",
    category: "Mídia",
    method: "api",
    auth: "none",
    capabilities: ["media"],
    params: ["query", "limit"],
    data: ["id", "title", "artist", "album", "duration", "rank", "url"],
    resource: "https://api.deezer.com/search (busca real; chart ainda em ponte)",
    status: "implemented",
    tosNote: "Busca pública sem chave; dados de faixa/artista/álbum. Chart (trending) segue como ponte do v1.",
  },
  {
    id: "openlibrary-trending",
    label: "Open Library (em alta)",
    group: "discover",
    category: "Conhecimento",
    method: "api",
    auth: "none",
    capabilities: ["trends", "custom"],
    params: ["period", "limit"],
    data: ["title", "author", "year", "score", "url"],
    resource: "https://openlibrary.org/trending/{daily|weekly|monthly}.json",
    status: "implemented",
  },
  {
    id: "npm-downloads",
    label: "npm downloads",
    group: "discover",
    category: "Código",
    method: "api",
    auth: "none",
    capabilities: ["code", "trends"],
    params: ["packages", "period", "limit"],
    data: ["package", "downloads", "period"],
    resource: "https://api.npmjs.org/downloads/point/{last-week}/{pkgs}",
    status: "implemented",
    tosNote: "Ate 20 pacotes por chamada.",
  },
  {
    id: "github-trending",
    label: "GitHub trending",
    group: "discover",
    category: "Código",
    method: "scrape",
    auth: "none",
    capabilities: ["code", "trends"],
    params: ["since", "language", "limit"],
    data: ["name", "description", "stars", "forks", "language", "url"],
    resource: "scraping https://github.com/trending?since=&language=",
    status: "implemented",
    tosNote: "Proxy via GitHub Search API (created recente + sort=stars); scraping direto bloqueado em datacenter.",
  },
  {
    id: "mastodon-trends",
    label: "Mastodon trends",
    group: "discover",
    category: "Social",
    method: "api",
    auth: "none",
    capabilities: ["social", "trends"],
    params: ["instance", "kind", "limit"],
    data: ["content", "author", "favourites", "url", "tags", "links"],
    resource: "https://{instance}/api/v1/trends/statuses|tags|links",
    status: "implemented",
    tosNote: "Instancia padrao mastodon.social.",
  },

  /* ---------------------------------------------------------- stores ----- */
  {
    id: "apple",
    label: "Apple App Store (reviews)",
    group: "stores",
    category: "Reviews",
    method: "api",
    auth: "none",
    capabilities: ["reviews", "media"],
    params: ["query", "country", "engine", "limit"],
    data: ["title", "rating", "author", "date", "version", "country", "helpful", "text"],
    resource: "amp-api apps.apple.com/api/apps/v1/catalog/{cc}/apps/{id}/reviews + RSS itunes customerreviews (fallback)",
    status: "implemented",
    tosNote: "amp-api primaria (l=pt-BR, sort mostRecent/mostHelpful por engine); RSS fallback. SSR sweep multi-pais do v1 nao portado (erro honesto se amp-api 429.; query = id do app).",
  },
  {
    id: "googleplay",
    label: "Google Play (reviews/apps)",
    group: "stores",
    category: "Reviews",
    method: "api",
    auth: "none",
    capabilities: ["reviews", "media"],
    params: ["query", "engine", "country", "limit"],
    data: ["title", "score", "author", "date", "version", "thumbsUp", "text", "appInfo"],
    resource: "scraping HTML publico /store/search + /store/apps/details (search|app); reviews exigem RPC batchexecute (honesto)",
    aliases: ["google", "discover-google-play"],
    status: "implemented",
    tosNote: "Padrao country br / lang pt_BR; engine = search|app (funcionam em datacenter); reviews = RPC pago/nao-embutido -> erro honesto.",
  },
  {
    id: "itunes-proxy",
    label: "iTunes/Apple proxy (passthrough)",
    group: "stores",
    category: "Infra",
    method: "other",
    auth: "none",
    capabilities: ["custom"],
    params: ["url"],
    data: ["raw"],
    resource: "allowlist ^https://(itunes|apps)\\.apple\\.com/",
    status: "implemented",
    tosNote: "Proxy pass-through so para hostnames Apple permitidos.",
  },

  /* ------------------------------------------------------- knowledge ----- */
  {
    id: "feed",
    label: "RSS/Atom (feed monitor)",
    group: "knowledge",
    category: "Monitoramento",
    method: "feed",
    auth: "none",
    capabilities: ["news", "custom"],
    params: ["url", "limit"],
    data: ["title", "text", "url", "author", "date", "feedUrl"],
    resource: "RSS 2.0 e Atom 1.0 (qualquer feed); descoberta via fonte web (acao feed)",
    status: "implemented",
    tosNote: "Requer URL do feed. Agregador multi-feed (OPML), monitoramento com diff de novos, full-text via fonte web quando o feed traz so resumo.",
  },
  {
    id: "paste",
    label: "Paste (entrada manual)",
    group: "knowledge",
    category: "Entrada manual",
    method: "other",
    auth: "none",
    capabilities: ["custom"],
    params: ["content", "limit"],
    data: ["title", "text"],
    resource: "qualquer texto colado vira dados Uni (linhas = itens)",
    status: "implemented",
    tosNote: "Requer texto. No pipeline multifonte e SKIP honesto por design (fontes que exigem texto sao puladas com razao).",
  },
  {
    id: "custom",
    label: "Fontes customizadas (qualquer JSON)",
    group: "knowledge",
    category: "Custom",
    method: "other",
    auth: "byok",
    capabilities: ["custom"],
    lookup: true,
    params: ["urlTemplate", "listPath", "fields", "query", "limit"],
    data: ["title", "text", "url", "author", "date", "score"],
    resource: "qualquer API publica JSON: urlTemplate {q}/{limit}, listPath dot-path, mapa de campos e auth opcional (header/query/bearer)",
    status: "implemented",
    tosNote: "A chave NUNCA e persistida no servidor (byok no browser). Templates prontos disponiveis.",
  },
  {
    id: "wikipedia",
    label: "Wikipedia (busca/artigo)",
    group: "knowledge",
    category: "Conhecimento",
    method: "api",
    auth: "none",
    capabilities: ["custom"],
    params: ["query", "action", "title", "limit"],
    data: ["title", "pageid", "snippet", "extract", "ns", "size", "wordcount", "timestamp"],
    resource: "https://pt.wikipedia.org/w/api.php?action=query list=search / prop=extracts",
    status: "implemented",
    tosNote: "Testado no v1 (6 itens demo).",
  },
  {
    id: "embed-search",
    label: "Resolução de URL (fanout)",
    group: "knowledge",
    category: "Infra",
    method: "api",
    auth: "none",
    capabilities: ["custom"],
    params: ["url"],
    data: ["kind", "id", "apiUrl", "fanoutTerm"],
    resource: "urlResolver.resolveUrl (youtube/wikipedia/github/npm/pypi/doi/apple/google/steam/openlibrary/mastodon/reddit)",
    status: "implemented",
    tosNote: "Roteador: caracteriza URL e devolve a fonte correspondente.",
  },
];

const byId = new Map<string, SourceCatalogEntry>(SOURCE_CATALOG.map((e) => [e.id, e]));

export function getSourceCatalogEntry(id: string): SourceCatalogEntry | undefined {
  return byId.get(id);
}

export function listSourceCatalog(): SourceCatalogEntry[] {
  return SOURCE_CATALOG;
}

export function catalogByGroup(group: SourceCatalogEntry["group"]): SourceCatalogEntry[] {
  return SOURCE_CATALOG.filter((e) => e.group === group);
}

/** ids únicos (validação rápida; o teste garante unicidade total). */
export function catalogCount(): number {
  return SOURCE_CATALOG.length;
}