/**
 * Registry — o catálogo central do Analysis Atlas.
 *
 * Cada módulo declara o contrato completo (input → processing → output →
 * evidence → confidence → score → visualization → canvas bridge). O Atlas é
 * um "Analysis OS": as metodologias são descritas, e cada uma aponta para a
 * infraestrutura que a realiza (nó do Canvas, seção de IA `experiment-analyze`,
 * ou análise determinística do `dashboardAnalytics`).
 *
 * `status`:
 *  - "available": roda HOJE (IA local/cloud ou determinístico).
 *  - "planned": framework declarado — metodologia definida, motor (NLP/
 *    embeddings/clustering) ainda não construído. Honestidade sobre o estado.
 *
 * Os IDs das seções de IA (canvas.section) batem com EXPERIMENT_SECTIONS /
 * SECTION_META do servidor (`summary`, `problems`, `requests`, `opportunities`,
 * `evidence`, `strategy`, `business`, `roi`, `qualitative`, `quantitative`,
 * `organize`, `suggestions`, `custom`, `lab-structured`).
 */
import {
  Boxes, Tags, Crosshair, DollarSign, CreditCard, Layers3, Network, GitCompare,
  MessageSquareText, Smile, Frown, Hash, Layers, Bug, Megaphone, Target,
  Repeat2, ArrowLeftRight, Users, Languages, Clock, TrendingUp, Gauge,
  GitBranch, Globe2, Map, Scale, ShieldCheck, ScrollText, FileOutput,
  LayoutDashboard, FileText, Database, Lightbulb, Rocket, Briefcase,
  type LucideIcon,
} from "lucide-react";
import type { AnalysisModule } from "./types";

export const ANALYSIS_MODULES: AnalysisModule[] = [
  /* ============================================================ APP ANALYTICS */
  {
    id: "app-profiling",
    label: "App Profiling", group: "app", icon: Boxes,
    tagline: "Classifica o app em business model, categoria, audiência e posicionamento.",
    description: "A partir dos metadados completos (descrição, categoria, preço, screenshots), classifica o app: modelo de negócio, categoria funcional, audiência-alvo, posicionamento e feature set.",
    input: ["app-metadata", "pricing"],
    processing: ["classification", "taxonomy mapping", "NLP", "LLM extraction"],
    parameters: ["fonte de metadados", "taxonomia base"],
    outputs: ["pattern", "need"],
    evidence: { claimExample: "O app é freemium fintech voltado a sub-30.", sourceType: "metadados + descrição" },
    confidence: "inference",
    visualization: ["markdown", "matrix"],
    canvas: { kind: "analyze", section: "organize", nodeLabel: "App Profiling" },
    status: "available", tags: ["metadados", "classificação"],
  },
  {
    id: "feature-extraction",
    label: "Feature Extraction", group: "app", icon: Tags,
    tagline: "Extrai funcionalidades declaradas da descrição, screenshots e reviews.",
    description: "Extrai funcionalidades (features) da descrição, screenshots e reviews via NLP/entity extraction e LLM. Base para a feature matrix e gap analysis.",
    input: ["app-metadata", "reviews"],
    processing: ["NLP", "entity extraction", "semantic classification", "LLM extraction"],
    parameters: ["fonte (descrição/screenshots/reviews)"],
    outputs: ["pattern"],
    evidence: { claimExample: "O app oferece biometria, PIX e cartão virtual.", sourceType: "citação da descrição/reviews" },
    confidence: "observation",
    visualization: ["table", "markdown"],
    canvas: { kind: "prompt", promptSeed: "Extraia a lista de funcionalidades (features) declaradas destes apps a partir da descrição e dos reviews. Organize em tabela.", nodeLabel: "Feature Extraction" },
    status: "available", tags: ["features", "nlp"],
  },
  {
    id: "feature-taxonomy",
    label: "Feature Taxonomy", group: "app", icon: Layers3,
    tagline: "Cria uma taxonomia hierárquica de features para comparar apps diferentes.",
    description: "Cria uma taxonomia hierárquica (ex.: Payments → PIX/Card/Transfer/Invoice; Security → Biometrics/2FA/Device verification) para comparar apps diferentes numa base comum.",
    input: ["competitor-features", "app-metadata"],
    processing: ["taxonomy mapping", "clustering semântico", "LLM extraction"],
    outputs: ["pattern"],
    evidence: { claimExample: "Pagamentos agrupa PIX, cartão e transferência.", sourceType: "features extraídas" },
    confidence: "inference",
    visualization: ["network", "matrix"],
    canvas: { kind: "prompt", promptSeed: "Construa uma taxonomia hierárquica de features a partir das funcionalidades destes apps. Agrupe por categoria (Pagamentos, Segurança, etc.).", nodeLabel: "Feature Taxonomy" },
    status: "available", tags: ["features", "taxonomia", "clustering"],
  },
  {
    id: "feature-matrix",
    label: "Feature Matrix", group: "app", icon: Layers3,
    tagline: "Matriz App × Feature: adoção, gaps e diferenciação vs. mercado.",
    description: "Matriz App × Feature revelando feature adoption, feature gaps, feature differentiation e o padrão de mercado (o que virou commodity).",
    input: ["competitor-features", "app-metadata"],
    processing: ["feature comparison", "frequency analysis"],
    outputs: ["pattern", "gap"],
    evidence: { claimExample: "Modo offline está em 2 de 5 apps concorrentes.", sourceType: "features extraídas" },
    confidence: "observation",
    visualization: ["matrix", "table"],
    canvas: { kind: "prompt", promptSeed: "Monte uma matriz App × Feature (✓/✗) a partir das funcionalidades dos apps. Destaque gaps e diferenciação.", nodeLabel: "Feature Matrix" },
    status: "available", tags: ["features", "matriz", "competitivo"],
  },
  {
    id: "app-positioning",
    label: "App Positioning Analysis", group: "app", icon: Crosshair,
    tagline: "Proposta de valor, posicionamento, audiência e percepção de categoria.",
    description: "Análise semântica de descrição, features, categoria, preço e reviews para derivar value proposition, positioning, target audience, differentiation, messaging e category perception.",
    input: ["app-metadata", "reviews", "pricing"],
    processing: ["semantic analysis", "embeddings", "keyword extraction", "clustering"],
    outputs: ["pattern", "gap"],
    evidence: { claimExample: "O app se posiciona como 'fintech sem tarifas'.", sourceType: "descrição + reviews" },
    confidence: "inference",
    visualization: ["markdown", "scatter"],
    canvas: { kind: "analyze", section: "strategy", nodeLabel: "Positioning" },
    status: "available", tags: ["posicionamento", "estratégia"],
  },
  {
    id: "competitive-analysis",
    label: "Competitive Analysis", group: "app", icon: GitCompare,
    tagline: "Concorrentes diretos/indiretos, forças, fraquezas, gaps e ameaças.",
    description: "Compara apps por similaridade, features, semântica, preço e reviews. Identifica direct/indirect competitors, strengths, weaknesses, feature/positioning gaps e competitive threats.",
    input: ["app-metadata", "competitor-features", "reviews", "pricing"],
    processing: ["similarity", "feature comparison", "semantic comparison", "review comparison"],
    outputs: ["pattern", "threat", "gap"],
    evidence: { claimExample: "App B supera App A em suporte e UX.", sourceType: "reviews comparativos" },
    confidence: "inference",
    visualization: ["matrix", "markdown", "network"],
    canvas: { kind: "analyze", section: "qualitative", nodeLabel: "Competitive" },
    status: "available", tags: ["competitivo", "comparativo"],
  },
  {
    id: "price-analysis",
    label: "Price Analysis", group: "app", icon: DollarSign,
    tagline: "Padrões de preço, posicionamento premium e price gaps.",
    description: "Cruza preço, assinatura, IAP, features, rating e reviews para revelar pricing patterns, premium positioning, price gaps e oportunidades de preço.",
    input: ["pricing", "app-metadata", "reviews"],
    processing: ["segmentation", "correlation", "regression", "price clustering"],
    outputs: ["pattern", "opportunity"],
    evidence: { claimExample: "Apps freemium com IAP concentram-se em games.", sourceType: "metadados de preço" },
    confidence: "observation",
    visualization: ["scatter", "bar", "markdown"],
    canvas: { kind: "prompt", promptSeed: "Analise o modelo de preço destes apps (grátis/freemium/pago/assinatura/IAP) e identifique padrões e gaps de preço.", nodeLabel: "Price Analysis" },
    status: "available", tags: ["preço", "monetização"],
  },
  {
    id: "monetization-analysis",
    label: "Monetization Analysis", group: "app", icon: CreditCard,
    tagline: "Detecta ads, subscription, freemium, paid app, IAP, trial.",
    description: "Detecta o modelo de monetização (ads, subscription, freemium, paid app, IAP, trial, premium) e deriva Business Model, Monetization Strategy e Market Distribution.",
    input: ["pricing", "app-metadata"],
    processing: ["classification", "rule-based detection"],
    outputs: ["pattern"],
    evidence: { claimExample: "70% dos apps do cluster usam IAP.", sourceType: "flags de monetização" },
    confidence: "observation",
    visualization: ["pie", "table"],
    canvas: { kind: "analyze", section: "business", nodeLabel: "Monetization" },
    status: "available", tags: ["monetização", "business"],
  },
  {
    id: "market-segmentation",
    label: "Market Segmentation", group: "app", icon: Layers,
    tagline: "Segmenta por categoria, preço, features, audiência, país, rating.",
    description: "Segmenta os apps por categoria, preço, funcionalidades, audiência, posicionamento, rating, tamanho, país e modelo de negócio.",
    input: ["app-metadata", "pricing", "countries"],
    processing: ["segmentation", "clustering"],
    outputs: ["pattern"],
    evidence: { claimExample: "Cluster 'fintech BR freemium' tem 4 apps.", sourceType: "metadados + país" },
    confidence: "inference",
    visualization: ["scatter", "matrix"],
    canvas: { kind: "prompt", promptSeed: "Segmente estes apps por categoria, preço, features e país. Nomeie cada segmento.", nodeLabel: "Segmentation" },
    status: "available", tags: ["segmentação", "cluster"],
  },
  {
    id: "market-clustering",
    label: "Market Clustering", group: "app", icon: Network,
    tagline: "Agrupa apps via K-means/hierárquico/DBSCAN + embeddings.",
    description: "Agrupa apps em clusters (Premium, Freemium, AI-first, Utility…) via K-means, hierarchical clustering, DBSCAN, embeddings, PCA, UMAP.",
    input: ["app-metadata", "reviews", "pricing"],
    processing: ["K-means", "hierarchical clustering", "DBSCAN", "embeddings", "PCA", "UMAP"],
    outputs: ["pattern"],
    evidence: { claimExample: "Cluster 2 agrupa apps freemium de produtividade.", sourceType: "embeddings + features" },
    confidence: "inference",
    visualization: ["scatter", "network"],
    canvas: { kind: "prompt", promptSeed: "Agrupe estes apps em clusters coerentes (estilo Premium/Freemium/AI-first/Utility) justificando cada agrupamento.", nodeLabel: "Clustering" },
    status: "available", tags: ["clustering", "embeddings"],
  },

  /* ========================================================= REVIEW ANALYTICS */
  {
    id: "review-sentiment",
    label: "Review Sentiment", group: "review", icon: MessageSquareText,
    tagline: "Positivo/Neutro/Negativo + Sentiment Score.",
    description: "Classifica sentimento (positivo/neutro/negativo) e intensidade a partir do texto + estrelas. Determinístico por nota hoje (★4-5 positivo, ★3 neutro, ★1-2 negativo); NLP de texto é planejado.",
    input: ["reviews"],
    processing: ["sentiment classification", "sentiment intensity"],
    parameters: ["base: nota | texto (planejado)"],
    outputs: ["pattern", "signal"],
    evidence: { claimExample: "62% dos reviews são positivos.", sourceType: "reviews", calculationExample: "positivos / total = 0.62" },
    confidence: "observation",
    visualization: ["pie", "bar"],
    canvas: { kind: "sentiment", nodeLabel: "Sentimento" },
    status: "available", tags: ["sentimento", "determinístico"],
  },
  {
    id: "aspect-sentiment",
    label: "Aspect-Based Sentiment", group: "review", icon: Layers,
    tagline: "Sentimento por aspecto (UX, Performance, Pricing, Support).",
    description: "Mais importante que sentimento geral: sentimento por aspecto (UX → negative, Performance → positive, Pricing → negative, Support → positive).",
    input: ["reviews"],
    processing: ["aspect extraction", "aspect sentiment", "NLP"],
    outputs: ["pattern", "problem", "signal"],
    evidence: { claimExample: "Sentimento em Pricing é 80% negativo.", sourceType: "reviews por aspecto" },
    confidence: "inference",
    visualization: ["heatmap", "matrix"],
    canvas: { kind: "analyze", section: "qualitative", nodeLabel: "Aspect Sentiment" },
    status: "available", tags: ["sentimento", "aspectos", "nlp"],
  },
  {
    id: "emotion-analysis",
    label: "Emotion Analysis", group: "review", icon: Smile,
    tagline: "Perfil emocional: frustração, raiva, satisfação, ansiedade…",
    description: "Classifica emoções (frustration, anger, disappointment, satisfaction, excitement, trust, anxiety, confusion, gratitude) e deriva um perfil emocional.",
    input: ["reviews"],
    processing: ["emotion classification", "NLP"],
    outputs: ["pattern", "signal"],
    evidence: { claimExample: "Frustração domina reviews de login.", sourceType: "reviews classificados" },
    confidence: "inference",
    visualization: ["bar", "heatmap"],
    canvas: { kind: "prompt", promptSeed: "Classifique a emoção dominante (frustração, raiva, decepção, satisfação, excitação, confiança, ansiedade, confusão, gratidão) nestes reviews e derive um perfil emocional.", nodeLabel: "Emotions" },
    status: "available", tags: ["emoção", "nlp"],
  },
  {
    id: "topic-modeling",
    label: "Topic Modeling", group: "review", icon: Hash,
    tagline: "Descobre tópicos via LDA/NMF/BERTopic + embeddings.",
    description: "Descobre tópicos (Login, Payments, Performance, Support, Pricing, Notifications) via LDA, NMF, BERTopic, embeddings, clustering semântico.",
    input: ["reviews"],
    processing: ["LDA", "NMF", "BERTopic", "embeddings", "clustering semântico"],
    outputs: ["pattern", "trend"],
    evidence: { claimExample: "Tópico 'pagamento' aparece em 18% dos reviews.", sourceType: "reviews + tópicos" },
    confidence: "inference",
    visualization: ["bar", "network"],
    canvas: { kind: "themes", nodeLabel: "Tópicos" },
    status: "available", tags: ["tópicos", "embeddings"],
  },
  {
    id: "theme-discovery",
    label: "Theme Discovery", group: "review", icon: Lightbulb,
    tagline: "Descobre temas emergentes (não pré-definidos).",
    description: "Descobre temas que NÃO estavam previamente definidos — evita uma taxonomia totalmente pré-programada. Hoje: nuvem de termos (determinístico); emergência semântica é planejada.",
    input: ["reviews"],
    processing: ["n-grams", "embeddings", "clustering semântico"],
    outputs: ["trend", "pattern"],
    evidence: { claimExample: "Termo 'dark mode' aparece 47 vezes.", sourceType: "frequência de termos" },
    confidence: "observation",
    visualization: ["wordcloud", "bar"],
    canvas: { kind: "themes", nodeLabel: "Temas" },
    status: "available", tags: ["temas", "emergente"],
  },
  {
    id: "pain-point-mining",
    label: "Pain Point Mining", group: "review", icon: Bug,
    tagline: "Detecta bugs, crashes, login, pagamento, UX, suporte, privacidade.",
    description: "Detecta pains (bugs, crashes, lentidão, login, pagamentos, UX, suporte, cobrança, anúncios, privacidade, segurança, funcionalidades ausentes) com Frequency, Severity, Affected Apps/Versions/Countries e Evidence.",
    input: ["reviews", "versions", "countries"],
    processing: ["NLP", "keyword matching", "LLM extraction"],
    outputs: ["problem", "pattern"],
    evidence: { claimExample: "Login é o maior pain (247 reviews, 10.2%).", sourceType: "reviews", calculationExample: "247 / 2431 = 10.2%" },
    confidence: "observation",
    score: { name: "Pain Severity", components: [
      { key: "frequency", label: "Frequência", weight: 0.4 },
      { key: "severity", label: "Severidade", weight: 0.4 },
      { key: "spread", label: "Apps/versões afetados", weight: 0.2 },
    ], formula: "Frequency × Severity × Spread" },
    visualization: ["bar", "heatmap", "markdown"],
    canvas: { kind: "analyze", section: "problems", nodeLabel: "Pain Points" },
    status: "available", tags: ["pain", "problemas"],
  },
  {
    id: "severity-analysis",
    label: "Severity Analysis", group: "review", icon: Frown,
    tagline: "Classifica P0–P3 ou escala contínua de severidade.",
    description: "Classifica pains em P0 (critical) / P1 (high) / P2 (medium) / P3 (low) ou escala contínua → Pain Severity Score.",
    input: ["reviews"],
    processing: ["classification", "rule-based", "LLM scoring"],
    outputs: ["problem"],
    evidence: { claimExample: "Crash em pagamento = P0.", sourceType: "reviews + severidade" },
    confidence: "inference",
    visualization: ["matrix", "bar"],
    canvas: { kind: "analyze", section: "problems", nodeLabel: "Severity" },
    status: "available", tags: ["severidade", "priorização"],
  },
  {
    id: "feature-request-mining",
    label: "Feature Request Mining", group: "review", icon: Megaphone,
    tagline: "Detecta 'adicionem…', 'gostaria…', 'falta…', 'por que não…'.",
    description: "Detecta frases de pedido de funcionalidade ('adicionem…', 'gostaria…', 'deveria ter…', 'falta…', 'por que não…') com Feature, Demand, Frequency, Users, Countries, Versions, Evidence.",
    input: ["reviews", "countries", "versions"],
    processing: ["pattern matching", "NLP", "intent detection"],
    outputs: ["desire", "need"],
    evidence: { claimExample: "'modo offline' pedido em 34 reviews.", sourceType: "reviews + intent" },
    confidence: "observation",
    visualization: ["bar", "table"],
    canvas: { kind: "analyze", section: "requests", nodeLabel: "Requests" },
    status: "available", tags: ["requests", "features"],
  },
  {
    id: "desire-mining",
    label: "Desire Mining", group: "review", icon: Target,
    tagline: "Diferencia feature ('modo offline') de desejo ('usar sem internet').",
    description: "Diferencia Feature ('quero modo offline') de Desire/outcome ('quero conseguir usar o app quando estou sem internet') extraindo desired outcome, motivation, context e user goal.",
    input: ["reviews"],
    processing: ["NLP", "outcome extraction", "LLM"],
    outputs: ["desire", "need"],
    evidence: { claimExample: "Desejo subjacente: autonomia offline.", sourceType: "reviews + outcomes" },
    confidence: "inference",
    visualization: ["markdown", "network"],
    canvas: { kind: "prompt", promptSeed: "Diferencie pedidos de feature de desejos/outcomes subjacentes nestes reviews. Para cada desejo, extraia outcome, motivação, contexto e user goal.", nodeLabel: "Desires" },
    status: "available", tags: ["desejos", "jtbd"],
  },
  {
    id: "jobs-to-be-done",
    label: "Jobs-to-be-Done", group: "review", icon: Repeat2,
    tagline: "Transforma reviews em 'When… I want… So that…'.",
    description: "Transforma reviews em Jobs estruturados (When… I want… So that…) — base para priorização orientada a progresso do usuário.",
    input: ["reviews"],
    processing: ["NLP", "LLM extraction", "JTBD framework"],
    outputs: ["need", "desire"],
    evidence: { claimExample: "Job: 'Quando abro o app de manhã, quero ver saldo rápido, pra decidir gastos.'", sourceType: "reviews → jobs" },
    confidence: "inference",
    visualization: ["markdown", "table"],
    canvas: { kind: "prompt", promptSeed: "Transforme estes reviews em Jobs-to-be-Done no formato 'When… I want… So that…'.", nodeLabel: "JTBD" },
    status: "available", tags: ["jtbd", "jobs"],
  },
  {
    id: "user-need-analysis",
    label: "User Need Analysis", group: "review", icon: Users,
    tagline: "Agrupa necessidades funcionais, emocionais, sociais, de confiança.",
    description: "Agrupa necessidades em functional, emotional, social, convenience, trust, control, speed, reliability, affordability.",
    input: ["reviews"],
    processing: ["classification", "clustering", "NLP"],
    outputs: ["need", "pattern"],
    evidence: { claimExample: "Necessidade de 'confiança' domina reviews de segurança.", sourceType: "reviews classificados" },
    confidence: "inference",
    visualization: ["matrix", "bar"],
    canvas: { kind: "prompt", promptSeed: "Agrupe as necessidades destes reviews em funcionais, emocionais, sociais, conveniência, confiança, controle, velocidade, confiabilidade, acessibilidade.", nodeLabel: "Needs" },
    status: "available", tags: ["necessidades", "needs"],
  },
  {
    id: "user-journey-analysis",
    label: "User Journey Analysis", group: "review", icon: Repeat2,
    tagline: "Mapeia fricção por etapa (Discovery→Install→…→Support).",
    description: "Identifica etapas da jornada (Discovery, Install, Signup, Onboarding, Activation, Usage, Payment, Retention, Support) e mede fricção por etapa.",
    input: ["reviews"],
    processing: ["NLP", "stage classification", "friction scoring"],
    outputs: ["problem", "pattern"],
    evidence: { claimExample: "Onboarding concentra 30% da fricção.", sourceType: "reviews por etapa" },
    confidence: "inference",
    visualization: ["timeline", "bar"],
    canvas: { kind: "prompt", promptSeed: "Mapeie estes reviews nas etapas da jornada (Discovery, Install, Signup, Onboarding, Activation, Usage, Payment, Retention, Support) e meça fricção por etapa.", nodeLabel: "Journey" },
    status: "available", tags: ["jornada", "funil"],
  },
  {
    id: "churn-analysis",
    label: "Churn Analysis", group: "review", icon: ArrowLeftRight,
    tagline: "Detecta intenção de uninstall, cancelamento, migração.",
    description: "Detecta churn signals (uninstall intention, cancellation, refund, migration, switching, abandonment, 'never again') com Reason, Severity, Competitor e Evidence.",
    input: ["reviews"],
    processing: ["intent detection", "NLP", "signal extraction"],
    outputs: ["signal", "threat"],
    evidence: { claimExample: "12 reviews mencionam uninstall intencional.", sourceType: "reviews + intent" },
    confidence: "observation",
    visualization: ["bar", "markdown"],
    canvas: { kind: "analyze", section: "business", nodeLabel: "Churn" },
    status: "available", tags: ["churn", "retenção"],
  },
  {
    id: "switching-analysis",
    label: "Switching Analysis", group: "review", icon: ArrowLeftRight,
    tagline: "Encontra 'Vou usar X em vez disso.'",
    description: "Encontra menções de switching ('Vou usar X em vez disso.') e deriva Competitor, Reason, Feature e Advantage percebida.",
    input: ["reviews"],
    processing: ["competitor mention extraction", "NLP"],
    outputs: ["signal", "threat"],
    evidence: { claimExample: "Usuários migrando para o App B por causa do modo offline.", sourceType: "reviews + menções" },
    confidence: "inference",
    visualization: ["network", "markdown"],
    canvas: { kind: "prompt", promptSeed: "Encontre menções de switching ('vou usar X em vez disso') nestes reviews e derive competidor, razão, feature e vantagem percebida.", nodeLabel: "Switching" },
    status: "available", tags: ["switching", "competitivo"],
  },
  {
    id: "competitor-mention",
    label: "Competitor Mention Analysis", group: "review", icon: GitCompare,
    tagline: "Extrai 'App A vs App B' e vantagem percebida por feature.",
    description: "Extrai comparações explícitas (App A vs App B) e mapeia vantagem percebida por feature (Feature X → B wins).",
    input: ["reviews", "competitor-features"],
    processing: ["NER", "relation extraction", "NLP"],
    outputs: ["threat", "pattern"],
    evidence: { claimExample: "Em suporte, App B vence App A em 80% das menções.", sourceType: "reviews comparativos" },
    confidence: "inference",
    visualization: ["network", "matrix"],
    canvas: { kind: "prompt", promptSeed: "Extraia comparações explícitas App A vs App B nestes reviews e mapeie vantagem percebida por feature.", nodeLabel: "Competitor Mentions" },
    status: "available", tags: ["competitivo", "menções"],
  },
  {
    id: "user-language",
    label: "User Language Analysis", group: "review", icon: Languages,
    tagline: "Descobre como o mercado fala (pain/benefit/feature/purchase).",
    description: "Descobre o vocabulário do mercado via n-grams, keywords, phrase mining, embeddings e clusters semânticos — pain language, benefit language, feature language, purchase language.",
    input: ["reviews"],
    processing: ["n-grams", "phrase mining", "embeddings", "semantic clusters"],
    outputs: ["pattern"],
    evidence: { claimExample: "Termo 'travar' aparece em 15% dos reviews negativos.", sourceType: "n-grams" },
    confidence: "observation",
    visualization: ["wordcloud", "table"],
    canvas: { kind: "themes", nodeLabel: "Linguagem" },
    status: "available", tags: ["linguagem", "aso"],
  },
  {
    id: "aso-intelligence",
    label: "ASO Intelligence", group: "review", icon: Megaphone,
    tagline: "Cruza descrição/keywords/screenshots/vocabulário → oportunidades ASO.",
    description: "Cruza description, keywords, categories, screenshots, user vocabulary, competitor vocabulary e ratings/reviews para keyword opportunities, messaging opportunities, feature terminology e positioning opportunities.",
    input: ["app-metadata", "reviews", "competitor-features"],
    processing: ["keyword extraction", "semantic comparison", "vocabulary crossing"],
    outputs: ["opportunity", "pattern"],
    evidence: { claimExample: "'cartão virtual' é termo de busca alto-volume não coberto.", sourceType: "vocabulário + metadados" },
    confidence: "inference",
    visualization: ["table", "markdown"],
    canvas: { kind: "prompt", promptSeed: "Cruze descrição, keywords e vocabulário dos usuários destes apps e sugira oportunidades de ASO (keywords, messaging, terminology).", nodeLabel: "ASO" },
    status: "available", tags: ["aso", "marketing"],
  },
  {
    id: "helpfulness-analysis",
    label: "Helpfulness Analysis", group: "review", icon: Gauge,
    tagline: "👍 do Google como proxy de salience.",
    description: "Usa thumbsUp do Google Play como proxy de salience: Frequency × Engagement = Salience. Highlighta pains/requests mais salientes (não só frequentes).",
    input: ["reviews", "helpfulness"],
    processing: ["frequency × engagement", "salience scoring"],
    outputs: ["signal", "pattern"],
    evidence: { claimExample: "Pain de login tem 500 👍 — alta salience.", sourceType: "thumbsUp + frequência" },
    confidence: "observation",
    visualization: ["bar", "scatter"],
    canvas: { kind: "reviews-analysis", nodeLabel: "Helpfulness" },
    status: "available", tags: ["salience", "google"],
  },
  {
    id: "review-quality",
    label: "Review Quality", group: "review", icon: ShieldCheck,
    tagline: "Classifica generic/informative/detailed/actionable/spam-like.",
    description: "Classifica reviews em generic, informative, detailed, actionable, spam-like → Evidence Quality Score. Filtra ruído antes de análises.",
    input: ["reviews"],
    processing: ["text classification", "length/heuristics", "NLP"],
    outputs: ["pattern"],
    evidence: { claimExample: "30% dos reviews são genéricos ('bom'/'ruim').", sourceType: "reviews classificados" },
    confidence: "observation",
    visualization: ["pie", "table"],
    canvas: { kind: "prompt", promptSeed: "Classifique estes reviews em generic, informative, detailed, actionable e spam-like e calcule um Evidence Quality Score.", nodeLabel: "Review Quality" },
    status: "available", tags: ["qualidade", "filtro"],
  },
  {
    id: "spam-anomaly",
    label: "Spam / Anomaly Detection", group: "review", icon: ShieldCheck,
    tagline: "Duplicatas, similaridade, burst, atividade anômala.",
    description: "Detecta duplicate detection, text similarity, burst detection, unusual patterns, anomaly detection → suspicious reviews, duplicate clusters, anomalous activity.",
    input: ["reviews"],
    processing: ["duplicate detection", "text similarity", "burst detection", "anomaly detection"],
    outputs: ["signal", "pattern"],
    evidence: { claimExample: "Cluster de 40 reviews idênticos em 2h.", sourceType: "similaridade + timestamp" },
    confidence: "observation",
    visualization: ["scatter", "network"],
    canvas: { kind: "code", promptSeed: "// Detecte duplicatas e bursts: normalize text, group by similarity, flag timestamps clusters.", nodeLabel: "Spam/Anomaly" },
    status: "available", tags: ["spam", "anomalia"],
  },

  /* ================================================================ TEMPORAL */
  {
    id: "temporal-analysis",
    label: "Temporal Analysis", group: "temporal", icon: Clock,
    tagline: "Rating, volume, sentimento, tópicos, pain ao longo do tempo.",
    description: "Analisa rating, review volume, sentimento, tópicos, pain, requests, churn e competitors ao longo do tempo via time series, moving averages, trend detection, seasonality, change-point detection.",
    input: ["reviews", "timeline"],
    processing: ["time series", "moving averages", "trend detection", "seasonality", "change-point detection"],
    outputs: ["trend", "pattern"],
    evidence: { claimExample: "Sentimento caiu 15% após release de maio.", sourceType: "timeline + sentimento" },
    confidence: "observation",
    visualization: ["line", "area"],
    canvas: { kind: "chart", chartType: "timeline", nodeLabel: "Timeline" },
    status: "available", tags: ["temporal", "timeline"],
  },
  {
    id: "emerging-trend",
    label: "Emerging Trend Detection", group: "temporal", icon: TrendingUp,
    tagline: "O que está começando a aparecer? Frequência atual vs. histórica.",
    description: "Pergunta: o que está começando a aparecer? Cruza frequência atual vs. histórica, growth e acceleration de tópicos/pains/requests.",
    input: ["reviews", "timeline"],
    processing: ["frequency delta", "growth rate", "acceleration"],
    outputs: ["trend", "opportunity"],
    evidence: { claimExample: "'dark mode' cresceu 3× no último mês.", sourceType: "frequência temporal" },
    confidence: "inference",
    visualization: ["line", "bar"],
    canvas: { kind: "chart", chartType: "timeline", nodeLabel: "Emerging Trends" },
    status: "available", tags: ["tendência", "emergente"],
  },
  {
    id: "review-velocity",
    label: "Review Velocity", group: "temporal", icon: Gauge,
    tagline: "Reviews/day, reviews/week, mentions/week.",
    description: "Mede reviews/day, reviews/week, mentions/week — proxy para issue velocity e engajamento.",
    input: ["reviews", "timeline"],
    processing: ["rate calculation", "moving averages"],
    outputs: ["signal", "pattern"],
    evidence: { claimExample: "Volume dobrou após polêmica de privacidade.", sourceType: "contagem temporal" },
    confidence: "observation",
    visualization: ["bar", "line"],
    canvas: { kind: "chart", chartType: "timeline", nodeLabel: "Velocity" },
    status: "available", tags: ["velocity", "volume"],
  },
  {
    id: "rating-trend",
    label: "Rating Trend", group: "temporal", icon: TrendingUp,
    tagline: "Não só '4.5', mas 4.7→4.6→4.3→4.0 (deterioration/improvement).",
    description: "Não apenas 'rating = 4.5', mas a trajetória (4.7→4.6→4.3→4.0) — rating deterioration / improvement.",
    input: ["reviews", "timeline"],
    processing: ["time series", "trend detection", "moving averages"],
    outputs: ["trend", "signal"],
    evidence: { claimExample: "Nota caiu 0.4 nos últimos 3 meses.", sourceType: "média temporal" },
    confidence: "observation",
    visualization: ["line", "area"],
    canvas: { kind: "chart", chartType: "timeline", nodeLabel: "Rating Trend" },
    status: "available", tags: ["rating", "tendência"],
  },
  {
    id: "version-impact",
    label: "Version Impact", group: "temporal", icon: GitBranch,
    tagline: "Versão × data × reviews antes/depois × sentimento × rating.",
    description: "Cruza Version, Release Date, Reviews Before/After, Sentiment, Topics e Rating via before/after, change-point, interrupted time series, topic shift → release impact, regression candidates, positive/negative changes.",
    input: ["reviews", "versions", "timeline"],
    processing: ["before/after comparison", "interrupted time series", "topic shift"],
    outputs: ["trend", "threat", "pattern"],
    evidence: { claimExample: "v3.2 introduziu regression em login (antes 2%, depois 8%).", sourceType: "reviews por versão" },
    confidence: "inference",
    visualization: ["bar", "line", "matrix"],
    canvas: { kind: "version-analysis", nodeLabel: "Version Impact" },
    status: "available", tags: ["versão", "regression"],
  },

  /* ===================================================================== GEO */
  {
    id: "country-analysis",
    label: "Country Analysis", group: "geo", icon: Globe2,
    tagline: "País × rating × review × tópico × app × versão.",
    description: "Cruza país, rating, review, tópico, app e versão → Country, Sentiment, Pain, Demand, Feature por país. Hoje: reviews carregam `country` (storefront).",
    input: ["reviews", "countries"],
    processing: ["groupby", "comparison"],
    outputs: ["pattern", "problem"],
    evidence: { claimExample: "Login é pain em 60% dos reviews BR.", sourceType: "reviews por país" },
    confidence: "observation",
    visualization: ["heatmap", "bar"],
    canvas: { kind: "reviews-analysis", nodeLabel: "Country" },
    status: "available", tags: ["geo", "país"],
  },
  {
    id: "cultural-localization",
    label: "Cultural / Localization", group: "geo", icon: Map,
    tagline: "Necessidades, linguagem, expectativas e regulação por país.",
    description: "Descobre necessidades específicas por país, linguagem local, expectativas, problemas de pagamento/regulatórios e hábitos de uso → localization opportunities.",
    input: ["reviews", "countries"],
    processing: ["cross-country comparison", "NLP", "regulatory keyword detection"],
    outputs: ["opportunity", "pattern"],
    evidence: { claimExample: "Usuários PT pedem método de pagamento específico.", sourceType: "reviews por país" },
    confidence: "inference",
    visualization: ["heatmap", "markdown"],
    canvas: { kind: "prompt", promptSeed: "Compare os reviews por país e identifique necessidades, linguagem e expectativas específicas de cada mercado.", nodeLabel: "Localization" },
    status: "available", tags: ["localização", "cultura"],
  },
  {
    id: "store-comparison",
    label: "Store Comparison", group: "geo", icon: GitCompare,
    tagline: "Apple × Google: rating, sentimento, tópicos, velocity.",
    description: "Compara Apple vs Google em rating, sentimento, tópicos, complaints, requests, versions, countries e review velocity → platform-specific intelligence.",
    input: ["reviews", "store-comparison"],
    processing: ["platform comparison", "groupby"],
    outputs: ["pattern", "gap"],
    evidence: { claimExample: "Apple tem nota média maior; Google tem mais volume.", sourceType: "reviews por loja" },
    confidence: "observation",
    visualization: ["bar", "matrix"],
    canvas: { kind: "chart", chartType: "store", nodeLabel: "Store Compare" },
    status: "available", tags: ["lojas", "comparativo"],
  },

  /* =============================================================== CROSS-DATA */
  {
    id: "cross-pain",
    label: "Cross-App Pain Analysis", group: "cross", icon: Bug,
    tagline: "Quais problemas aparecem em VÁRIOS apps? (market-wide).",
    description: "Muito mais interessante que o problema de um único app: quais problemas aparecem em vários apps? → Market-wide Pain com frequency, severity e affected apps.",
    input: ["reviews"],
    processing: ["cross-app aggregation", "pain clustering"],
    outputs: ["problem", "pattern"],
    evidence: { claimExample: "Login lento aparece em 4 de 5 fintechs.", sourceType: "reviews cross-app" },
    confidence: "inference",
    visualization: ["heatmap", "bar"],
    canvas: { kind: "analyze", section: "problems", nodeLabel: "Cross-App Pain" },
    status: "available", tags: ["cross-app", "pain"],
  },
  {
    id: "cross-desire",
    label: "Cross-App Desire Analysis", group: "cross", icon: Target,
    tagline: "O que usuários de vários apps estão pedindo? (market-wide demand).",
    description: "Quais desejos/requests aparecem em vários apps? → Market-wide demand (não só demanda de um app).",
    input: ["reviews", "user-requests"],
    processing: ["cross-app aggregation", "request clustering"],
    outputs: ["desire", "pattern"],
    evidence: { claimExample: "Modo offline pedido em 3 apps concorrentes.", sourceType: "requests cross-app" },
    confidence: "inference",
    visualization: ["bar", "table"],
    canvas: { kind: "analyze", section: "requests", nodeLabel: "Cross-App Desire" },
    status: "available", tags: ["cross-app", "demanda"],
  },
  {
    id: "feature-gap",
    label: "Feature Gap Analysis", group: "cross", icon: Layers3,
    tagline: "Cruza features de concorrentes + requests + próprias features.",
    description: "Cruza Competitor Features + User Requests + Own Features → Missing Feature, Demand, Competition, Evidence.",
    input: ["competitor-features", "user-requests", "app-metadata"],
    processing: ["feature comparison", "gap detection"],
    outputs: ["gap", "opportunity"],
    evidence: { claimExample: "App A não tem exportação CSV pedida por 30 reviews e presente em B.", sourceType: "features + requests" },
    confidence: "inference",
    visualization: ["matrix", "markdown"],
    canvas: { kind: "prompt", promptSeed: "Cruze features dos concorrentes, requests dos usuários e as próprias features destes apps e identifique feature gaps (missing feature, demand, competition, evidence).", nodeLabel: "Feature Gap" },
    status: "available", tags: ["gap", "features"],
  },
  {
    id: "white-space",
    label: "White Space Discovery", group: "cross", icon: Lightbulb,
    tagline: "Demand × Competition × Feature Availability = mercado underserved.",
    description: "Cruza Demand × Competition × Feature Availability → unserved / underserved market.",
    input: ["user-requests", "competitor-features", "app-metadata"],
    processing: ["demand × competition matrix", "gap scoring"],
    outputs: ["gap", "opportunity"],
    evidence: { claimExample: "Alta demanda, baixa competição e sem oferta → white space.", sourceType: "matriz demanda×competição" },
    confidence: "inference",
    visualization: ["scatter", "matrix"],
    canvas: { kind: "prompt", promptSeed: "Cruze demanda, competição e disponibilidade de features para descobrir white spaces (mercado underserved).", nodeLabel: "White Space" },
    status: "available", tags: ["white space", "oportunidade"],
  },
  {
    id: "opportunity-scoring",
    label: "Opportunity Scoring", group: "cross", icon: Target,
    tagline: "Demand × Severity × Growth × Competitive Gap × Strategic Fit ÷ Effort.",
    description: "Score composto de oportunidade — CADA componente guardado separadamente, nunca só o número final. Formula: Demand × Severity × Growth × Competitive Gap × Strategic Fit ÷ Effort.",
    input: ["user-requests", "competitor-features", "pricing"],
    processing: ["composite scoring", "normalization"],
    outputs: ["opportunity"],
    evidence: { claimExample: "Opportunity Score 78/100 (demand 80, severity 70, gap 90, fit 85, effort 30).", sourceType: "componentes do score" },
    confidence: "hypothesis",
    score: { name: "Opportunity Score", components: [
      { key: "demand", label: "Demanda", weight: 0.25 },
      { key: "severity", label: "Severidade", weight: 0.2 },
      { key: "growth", label: "Crescimento", weight: 0.15 },
      { key: "competitiveGap", label: "Gap competitivo", weight: 0.2 },
      { key: "strategicFit", label: "Fit estratégico", weight: 0.15 },
      { key: "effort", label: "Esforço (inverso)", weight: 0.05 },
    ], formula: "Demand × Severity × Growth × Competitive Gap × Strategic Fit ÷ Effort" },
    visualization: ["scatter", "bar", "matrix"],
    canvas: { kind: "analyze", section: "opportunities", nodeLabel: "Opportunity Score" },
    status: "available", tags: ["score", "oportunidade"],
  },
  {
    id: "retention-opportunity",
    label: "Retention Opportunity", group: "cross", icon: Repeat2,
    tagline: "Pain + churn signal + frequência + segmento afetado.",
    description: "Cruza Pain + Churn signal + Frequency + Affected segment → retention opportunities.",
    input: ["reviews"],
    processing: ["cross-signal aggregation", "segmentation"],
    outputs: ["opportunity", "signal"],
    evidence: { claimExample: "Login lento + churn signal em 12% dos reviews de onboarding.", sourceType: "pain + churn" },
    confidence: "hypothesis",
    visualization: ["matrix", "markdown"],
    canvas: { kind: "analyze", section: "opportunities", nodeLabel: "Retention" },
    status: "available", tags: ["retenção", "oportunidade"],
  },
  {
    id: "monetization-opportunity",
    label: "Monetization Opportunity", group: "cross", icon: DollarSign,
    tagline: "Desire + pain + WTP evidence + competitive pricing.",
    description: "Cruza Desire + Pain + Willingness-to-pay evidence + Competitive pricing → potential monetization opportunities.",
    input: ["reviews", "pricing", "competitor-features"],
    processing: ["WTP detection", "cross-signal"],
    outputs: ["opportunity"],
    evidence: { claimExample: "Usuários expressam WTP por exportação avançada.", sourceType: "reviews + pricing" },
    confidence: "hypothesis",
    visualization: ["matrix", "markdown"],
    canvas: { kind: "analyze", section: "business", nodeLabel: "Monetization Opp" },
    status: "available", tags: ["monetização", "oportunidade"],
  },

  /* ============================================================ INTELLIGENCE */
  {
    id: "product-intelligence",
    label: "Product Intelligence", group: "intelligence", icon: Lightbulb,
    tagline: "Combina pain, desire, JTBD, frequência, severidade, segmento.",
    description: "Combina Pain + Desire + JTBD + Frequency + Severity + Segment + Competition → problem statement, user segment, job, opportunity e evidence.",
    input: ["reviews", "user-requests"],
    processing: ["multi-signal synthesis", "JTBD", "segmentation"],
    outputs: ["opportunity", "problem", "need"],
    evidence: { claimExample: "Problem statement + segment + job consolidados.", sourceType: "síntese de múltiplos sinais" },
    confidence: "hypothesis",
    visualization: ["markdown", "matrix"],
    canvas: { kind: "analyze", section: "strategy", nodeLabel: "Product Intel" },
    status: "available", tags: ["produto", "síntese"],
  },
  {
    id: "marketing-intelligence",
    label: "Marketing Intelligence", group: "intelligence", icon: Megaphone,
    tagline: "Linguagem, pain, outcomes, objeções, benefits → messaging/copy.",
    description: "Extrai language, pain, desired outcomes, objections, benefits e competitor complaints → messaging, landing page ideas, ad angles, positioning, copy opportunities.",
    input: ["reviews", "app-metadata"],
    processing: ["language extraction", "objection mining", "benefit mining"],
    outputs: ["opportunity", "pattern"],
    evidence: { claimExample: "Objeção 'caro' aparece em 40% dos reviews negativos.", sourceType: "reviews + objeções" },
    confidence: "inference",
    visualization: ["markdown", "table"],
    canvas: { kind: "prompt", promptSeed: "Extraia linguagem, pain, outcomes desejados, objeções e benefits destes reviews e gere oportunidades de messaging/copy.", nodeLabel: "Marketing Intel" },
    status: "available", tags: ["marketing", "copy"],
  },
  {
    id: "sales-intelligence",
    label: "Sales Intelligence", group: "intelligence", icon: Briefcase,
    tagline: "Pain, complaints, switching triggers, buyer objections.",
    description: "Identifica pain points, complaints about existing solutions, switching triggers, buyer objections, desired capabilities → sales arguments / objections / triggers.",
    input: ["reviews"],
    processing: ["trigger mining", "objection extraction"],
    outputs: ["signal", "opportunity"],
    evidence: { claimExample: "Switching trigger: 'suporte do App A é demorado'.", sourceType: "reviews + triggers" },
    confidence: "inference",
    visualization: ["markdown", "table"],
    canvas: { kind: "prompt", promptSeed: "Identifique pain points, complaints, switching triggers, buyer objections e desired capabilities destes reviews e gere argumentos/gatilhos de venda.", nodeLabel: "Sales Intel" },
    status: "available", tags: ["vendas", "triggers"],
  },
  {
    id: "support-intelligence",
    label: "Customer Support Intelligence", group: "intelligence", icon: ShieldCheck,
    tagline: "Issues recorrentes, doc gaps, onboarding confusion → FAQ/automation.",
    description: "Agrupa recurring issues, support problems, documentation gaps e onboarding confusion → FAQ opportunities, documentation opportunities, automation opportunities, support priorities.",
    input: ["reviews"],
    processing: ["clustering", "gap detection"],
    outputs: ["problem", "opportunity"],
    evidence: { claimExample: "Confusão de onboarding em 25% dos reviews.", sourceType: "reviews + onboarding" },
    confidence: "inference",
    visualization: ["table", "markdown"],
    canvas: { kind: "prompt", promptSeed: "Agrupe recurring issues, doc gaps e onboarding confusion destes reviews e sugira oportunidades de FAQ, documentação e automação.", nodeLabel: "Support Intel" },
    status: "available", tags: ["suporte", "faq"],
  },
  {
    id: "qa-intelligence",
    label: "QA Intelligence", group: "intelligence", icon: Bug,
    tagline: "Crash/Bug/Error × versão × device × OS → bug clusters.",
    description: "Especialmente crash, bug, error, version, device, OS → bug cluster, severity, version, frequency, evidence.",
    input: ["reviews", "versions"],
    processing: ["bug clustering", "device/OS correlation"],
    outputs: ["problem", "pattern"],
    evidence: { claimExample: "Crash em iOS 17 + v3.2 = cluster P0.", sourceType: "reviews + versão/OS" },
    confidence: "observation",
    visualization: ["matrix", "bar"],
    canvas: { kind: "analyze", section: "problems", nodeLabel: "QA Intel" },
    status: "available", tags: ["qa", "bugs"],
  },
  {
    id: "release-intelligence",
    label: "Release Intelligence", group: "intelligence", icon: GitBranch,
    tagline: "Antes do release: known pain/requests. Depois: novo sentimento.",
    description: "Antes do release: known pain + known requests. Depois: new reviews, new sentiment, new problems → release impact report.",
    input: ["reviews", "versions", "timeline"],
    processing: ["before/after", "change-point"],
    outputs: ["trend", "threat"],
    evidence: { claimExample: "Release introduziu 3 novos pains não presentes antes.", sourceType: "reviews antes/depois" },
    confidence: "inference",
    visualization: ["line", "markdown"],
    canvas: { kind: "version-analysis", nodeLabel: "Release Intel" },
    status: "available", tags: ["release", "impact"],
  },
  {
    id: "venture-intelligence",
    label: "Investment / Venture Intelligence", group: "intelligence", icon: TrendingUp,
    tagline: "Market growth + demand + competition + emerging features → espaços.",
    description: "Cruza market growth, app growth proxies, demand, competition, user pain, emerging features e category expansion → emerging categories, crowded categories, underserved categories, potential startup spaces.",
    input: ["reviews", "app-metadata", "pricing"],
    processing: ["market sizing proxies", "category analysis"],
    outputs: ["opportunity", "trend"],
    evidence: { claimExample: "Categoria 'AI-first' cresce com demanda e baixa competição.", sourceType: "demand + competition" },
    confidence: "hypothesis",
    visualization: ["scatter", "matrix"],
    canvas: { kind: "prompt", promptSeed: "Cruze market growth proxies, demanda, competição, emerging features e category expansion destes apps e identifique categorias emergentes/underserved.", nodeLabel: "Venture Intel" },
    status: "available", tags: ["venture", "mercado"],
  },
  {
    id: "product-idea-generator",
    label: "Product Idea Generator", group: "intelligence", icon: Rocket,
    tagline: "Evidence → need → unmet need → gap → product concept.",
    description: "NÃO 'a IA inventou uma ideia.' É Evidence → User Need → Unmet Need → Market Gap → Product Concept com Problem, Target User, Job, Solution, Differentiator, Evidence, Competition, Business Model.",
    input: ["reviews", "user-requests", "competitor-features"],
    processing: ["evidence synthesis", "gap mapping", "concept generation"],
    outputs: ["opportunity", "desire"],
    evidence: { claimExample: "Product concept derivado de gap + demanda + WTP.", sourceType: "evidence chain" },
    confidence: "hypothesis",
    visualization: ["markdown"],
    canvas: { kind: "prompt", promptSeed: "A partir de evidence → user need → unmet need → market gap, gere um product concept (problem, target user, job, solution, differentiator, evidence, competition, business model).", nodeLabel: "Product Idea" },
    status: "available", tags: ["produto", "ideia"],
  },
  {
    id: "niche-discovery",
    label: "Niche Discovery", group: "intelligence", icon: Target,
    tagline: "audiência específica + problema + competição fraca.",
    description: "Encontra combinações de specific audience + specific problem + weak competition → potential niche.",
    input: ["reviews", "competitor-features"],
    processing: ["audience + problem + competition matching"],
    outputs: ["opportunity"],
    evidence: { claimExample: "Niche: freelancers com pain de relatório fiscal.", sourceType: "audiência + pain" },
    confidence: "hypothesis",
    visualization: ["matrix", "markdown"],
    canvas: { kind: "prompt", promptSeed: "Encontre combinações de audiência específica + problema específico + competição fraca nestes reviews e identifique potenciais nichos.", nodeLabel: "Niche" },
    status: "available", tags: ["nicho", "oportunidade"],
  },
  {
    id: "micro-saas-discovery",
    label: "Micro-SaaS Discovery", group: "intelligence", icon: Rocket,
    tagline: "Pain + workflow repetido + WTP + baixa competição.",
    description: "Gera Pain + Repeated workflow + Willingness to pay + Low competition → Micro-SaaS hypothesis.",
    input: ["reviews", "user-requests"],
    processing: ["workflow detection", "WTP + competition matching"],
    outputs: ["opportunity"],
    evidence: { claimExample: "Hipótese micro-SaaS para automação de relatório.", sourceType: "pain + workflow + WTP" },
    confidence: "hypothesis",
    visualization: ["markdown", "table"],
    canvas: { kind: "prompt", promptSeed: "A partir de pain + workflow repetido + WTP + baixa competição, gere hipóteses de micro-SaaS.", nodeLabel: "Micro-SaaS" },
    status: "available", tags: ["micro-saas", "oportunidade"],
  },
  {
    id: "market-opportunity",
    label: "Market Opportunity Discovery", group: "intelligence", icon: TrendingUp,
    tagline: "Demanda grande + crescente + oferta ruim + pain alto.",
    description: "Cruza large demand + growing demand + poor supply + high pain → market opportunity.",
    input: ["reviews", "competitor-features"],
    processing: ["demand × supply × pain matching"],
    outputs: ["opportunity"],
    evidence: { claimExample: "Mercado com alta demanda crescente e oferta pobre.", sourceType: "demand + supply + pain" },
    confidence: "hypothesis",
    visualization: ["scatter", "markdown"],
    canvas: { kind: "prompt", promptSeed: "Cruze demanda grande + crescente + oferta ruim + pain alto destes reviews/apps e identifique market opportunities.", nodeLabel: "Market Opp" },
    status: "available", tags: ["mercado", "oportunidade"],
  },
  {
    id: "market-research",
    label: "Market Research", group: "intelligence", icon: Globe2,
    tagline: "Gera market map, competitors, segments, feature/pricing landscape.",
    description: "Gera automaticamente market map, competitors, segments, feature landscape, pricing landscape, demand landscape, emerging trends e gaps.",
    input: ["app-metadata", "reviews", "pricing", "competitor-features"],
    processing: ["landscape synthesis", "segmentation", "clustering"],
    outputs: ["pattern", "opportunity", "gap"],
    evidence: { claimExample: "Market map consolidando 5 apps em 3 segmentos.", sourceType: "metadados + reviews + preço" },
    confidence: "inference",
    visualization: ["network", "matrix", "markdown"],
    canvas: { kind: "analyze", section: "summary", nodeLabel: "Market Research" },
    status: "available", tags: ["mercado", "research"],
  },

  /* ============================================================= DISCOVERY */
  {
    id: "discovery-problems",
    label: "Problems Discovery", group: "discovery", icon: Bug,
    tagline: "Bugs, friction, pain, complaints — consolidado.",
    description: "Consolida problemas descobertos: bugs, friction, pain, complaints — o output canônico de várias análises de pain.",
    input: ["reviews"],
    processing: ["aggregation"],
    outputs: ["problem"],
    evidence: { claimExample: "Top 5 problems consolidados.", sourceType: "múltiplas análises" },
    confidence: "observation",
    visualization: ["bar", "markdown"],
    canvas: { kind: "analyze", section: "problems", nodeLabel: "Problems" },
    status: "available", tags: ["descoberta", "problemas"],
  },
  {
    id: "discovery-needs",
    label: "Needs Discovery", group: "discovery", icon: Users,
    tagline: "Necessidades funcionais, emocionais, contextuais.",
    description: "Consolida necessidades: functional, emotional, contextual.",
    input: ["reviews"],
    processing: ["aggregation", "classification"],
    outputs: ["need"],
    evidence: { claimExample: "Top necessidades funcionais e emocionais.", sourceType: "reviews classificados" },
    confidence: "inference",
    visualization: ["matrix", "markdown"],
    canvas: { kind: "analyze", section: "requests", nodeLabel: "Needs" },
    status: "available", tags: ["descoberta", "necessidades"],
  },
  {
    id: "discovery-opportunities",
    label: "Opportunities Discovery", group: "discovery", icon: Target,
    tagline: "Produto, mercado, monetização, retenção.",
    description: "Consolida oportunidades de produto, mercado, monetização e retenção.",
    input: ["reviews", "user-requests"],
    processing: ["aggregation", "scoring"],
    outputs: ["opportunity"],
    evidence: { claimExample: "Top oportunidades ranqueadas por score.", sourceType: "scores compostos" },
    confidence: "hypothesis",
    score: { name: "Opportunity Score", components: [
      { key: "demand", label: "Demanda" },
      { key: "severity", label: "Severidade" },
      { key: "growth", label: "Crescimento" },
      { key: "competitiveGap", label: "Gap competitivo" },
      { key: "strategicFit", label: "Fit estratégico" },
      { key: "effort", label: "Esforço (inverso)" },
    ], formula: "Demand × Severity × Growth × Gap × Fit ÷ Effort" },
    visualization: ["scatter", "bar"],
    canvas: { kind: "analyze", section: "opportunities", nodeLabel: "Opportunities" },
    status: "available", tags: ["descoberta", "oportunidades"],
  },
  {
    id: "discovery-threats",
    label: "Threats Discovery", group: "discovery", icon: Frown,
    tagline: "Competidor, churn, regression, emerging negative trend.",
    description: "Consolida ameaças: competitor, churn, regression, emerging negative trend.",
    input: ["reviews", "timeline"],
    processing: ["aggregation", "signal detection"],
    outputs: ["threat"],
    evidence: { claimExample: "Regression detectado após release + churn signal.", sourceType: "múltiplos sinais" },
    confidence: "inference",
    visualization: ["matrix", "markdown"],
    canvas: { kind: "analyze", section: "strategy", nodeLabel: "Threats" },
    status: "available", tags: ["descoberta", "ameaças"],
  },
  {
    id: "discovery-trends",
    label: "Trends Discovery", group: "discovery", icon: TrendingUp,
    tagline: "Demanda emergente, tecnologia, mudança de percepção.",
    description: "Consolida tendências: emerging demand, emerging technology, changing perception.",
    input: ["reviews", "timeline"],
    processing: ["aggregation", "trend detection"],
    outputs: ["trend"],
    evidence: { claimExample: "Tendência emergente de 'AI assistance'.", sourceType: "frequência temporal" },
    confidence: "inference",
    visualization: ["line", "bar"],
    canvas: { kind: "chart", chartType: "timeline", nodeLabel: "Trends" },
    status: "available", tags: ["descoberta", "tendências"],
  },
  {
    id: "discovery-gaps",
    label: "Gaps Discovery", group: "discovery", icon: Layers3,
    tagline: "Feature gap, market gap, positioning gap, experience gap.",
    description: "Consolida gaps: feature gap, market gap, positioning gap, experience gap.",
    input: ["reviews", "competitor-features"],
    processing: ["aggregation", "gap detection"],
    outputs: ["gap"],
    evidence: { claimExample: "Experience gap em onboarding mobile.", sourceType: "reviews + features" },
    confidence: "inference",
    visualization: ["matrix", "markdown"],
    canvas: { kind: "prompt", promptSeed: "Consolide gaps (feature, market, positioning, experience) destes apps/reviews.", nodeLabel: "Gaps" },
    status: "available", tags: ["descoberta", "gaps"],
  },

  /* ============================================================= EVIDENCE */
  {
    id: "evidence-engine",
    label: "Evidence Engine", group: "evidence", icon: ScrollText,
    tagline: "Claim → Evidence → Source → Review IDs → Calculation → Confidence.",
    description: "Camada CENTRAL. Toda descoberta tem Claim → Evidence → Source → Review IDs → Calculation → Confidence. Ex.: CLAIM 'Login é pain major' / EVIDENCE 247 reviews / CALC 247/2431=10.2% / CONFIDENCE High.",
    input: ["reviews"],
    processing: ["claim grounding", "citation extraction", "calculation"],
    outputs: ["problem", "pattern"],
    evidence: { claimExample: "Login é pain major (247/2431 = 10.2%, confiança alta).", sourceType: "review IDs + cálculo" },
    confidence: "observation",
    visualization: ["markdown", "table"],
    canvas: { kind: "analyze", section: "evidence", nodeLabel: "Evidence" },
    status: "available", tags: ["evidência", "confiança"],
  },
  {
    id: "confidence-engine",
    label: "Confidence Engine", group: "evidence", icon: ShieldCheck,
    tagline: "Separa observação, inferência, hipótese e previsão.",
    description: "Separa Observation (18% mencionam login) de Inference (login é problema relevante) de Hypothesis (corrigir login reduz churn) de Prediction (pode reduzir churn em X%). Fundamental para não tratar estimativa como fato.",
    input: ["reviews"],
    processing: ["level labeling", "claim classification"],
    outputs: ["signal", "pattern"],
    evidence: { claimExample: "Observação ≠ Inferência ≠ Hipótese ≠ Previsão.", sourceType: "claims + níveis" },
    confidence: "observation",
    visualization: ["matrix", "markdown"],
    canvas: { kind: "prompt", promptSeed: "Para cada afirmação destes reviews, rotule o nível de confiança: observação, inferência, hipótese ou previsão. Nunca trate estimativa como fato.", nodeLabel: "Confidence" },
    status: "available", tags: ["confiança", "honestidade"],
  },

  /* ============================================================= DECISION */
  {
    id: "product-prioritization",
    label: "Product Prioritization", group: "decision", icon: Scale,
    tagline: "RICE, ICE, WSJF, MoSCoW, Value vs Effort.",
    description: "Frameworks de priorização: RICE, ICE, WSJF, MoSCoW, Value vs Effort, Impact vs Confidence, Opportunity Scoring → Priority, Impact, Effort, Confidence, Evidence.",
    input: ["reviews", "user-requests"],
    processing: ["scoring frameworks", "impact/effort"],
    outputs: ["opportunity"],
    evidence: { claimExample: "Iniciativa X: RICE 42, esforço M, confiança alta.", sourceType: "score framework" },
    confidence: "hypothesis",
    score: { name: "RICE", components: [
      { key: "reach", label: "Reach" },
      { key: "impact", label: "Impact" },
      { key: "confidence", label: "Confidence" },
      { key: "effort", label: "Effort" },
    ], formula: "(Reach × Impact × Confidence) ÷ Effort" },
    visualization: ["matrix", "table"],
    canvas: { kind: "analyze", section: "roi", nodeLabel: "Prioritization" },
    status: "available", tags: ["priorização", "rice"],
  },
  {
    id: "roi-analysis",
    label: "ROI Analysis", group: "decision", icon: TrendingUp,
    tagline: "Demanda + usuários afetados + severidade + retenção + esforço.",
    description: "Cruza user demand, affected users, pain severity, potential retention, monetization e development effort → Potential ROI. IMPORTANTE: distinguir evidence-backed de model-generated estimate.",
    input: ["reviews", "user-requests"],
    processing: ["ROI modeling", "effort estimation"],
    outputs: ["opportunity"],
    evidence: { claimExample: "ROI potencial da iniciativa Y (evidence-backed vs estimate).", sourceType: "demanda + esforço" },
    confidence: "prediction",
    score: { name: "ROI", components: [
      { key: "demand", label: "Demanda" },
      { key: "affectedUsers", label: "Usuários afetados" },
      { key: "severity", label: "Severidade" },
      { key: "retention", label: "Retenção potencial" },
      { key: "monetization", label: "Monetização" },
      { key: "effort", label: "Esforço (inverso)" },
    ], formula: "(Demand × Users × Severity × Retention × Monetization) ÷ Effort" },
    visualization: ["scatter", "table"],
    canvas: { kind: "analyze", section: "roi", nodeLabel: "ROI" },
    status: "available", tags: ["roi", "priorização"],
  },

  /* ============================================================= OUTPUT */
  {
    id: "reporting-engine",
    label: "Reporting Engine", group: "output", icon: FileOutput,
    tagline: "Qualquer análise → dados (JSON/CSV), visual, documento (MD/PDF).",
    description: "Qualquer análise pode produzir dados (JSON/CSV/Parquet), visual (table/bar/line/area/pie/heatmap/scatter/network/map/timeline/matrix) ou documento (Markdown/PDF/executive/competitive report).",
    input: ["reviews", "app-metadata"],
    processing: ["rendering", "export"],
    outputs: ["pattern"],
    evidence: { claimExample: "Relatório executivo consolidado.", sourceType: "outputs de análises" },
    confidence: "observation",
    visualization: ["table", "markdown", "bar"],
    canvas: { kind: "report", promptSeed: "Gere um relatório executivo consolidando os achados principais destes apps/reviews.", nodeLabel: "Report" },
    status: "available", tags: ["report", "export"],
  },
  {
    id: "dashboard-output",
    label: "Dashboard Output", group: "output", icon: LayoutDashboard,
    tagline: "KPIs + múltiplos gráficos consolidados.",
    description: "Painel com KPIs + múltiplos gráficos sobre os dados conectados (rating, sentimento, lojas, por app).",
    input: ["reviews", "app-metadata"],
    processing: ["aggregation", "rendering"],
    outputs: ["pattern"],
    evidence: { claimExample: "Dashboard com 4 gráficos + KPIs.", sourceType: "dados agregados" },
    confidence: "observation",
    visualization: ["bar", "pie", "line", "matrix"],
    canvas: { kind: "dashboard", nodeLabel: "Dashboard" },
    status: "available", tags: ["dashboard", "output"],
  },
  {
    id: "dataset-output",
    label: "Dataset Output", group: "output", icon: Database,
    tagline: "Exporta o dataset bruto (JSON/CSV).",
    description: "Exporta o dataset bruto coletado — exatamente o que está em `aso:dataset:v1` — para reuso/análise externa.",
    input: ["reviews", "app-metadata"],
    processing: ["serialization"],
    outputs: ["pattern"],
    evidence: { claimExample: "Dataset completo exportado.", sourceType: "aso:dataset:v1" },
    confidence: "observation",
    visualization: ["table"],
    canvas: { kind: "table", nodeLabel: "Dataset" },
    status: "available", tags: ["dataset", "export"],
  },
];

/** Lookup por id. */
export function getModule(id: string): AnalysisModule | undefined {
  return ANALYSIS_MODULES.find((m) => m.id === id);
}

/** Módulos de um grupo (na ordem do registry). */
export function modulesByGroup(group: AnalysisModule["group"]): AnalysisModule[] {
  return ANALYSIS_MODULES.filter((m) => m.group === group);
}

/** Busca textual em label/tagline/description/tags. */
export function searchModules(query: string): AnalysisModule[] {
  const q = query.trim().toLowerCase();
  if (!q) return ANALYSIS_MODULES;
  return ANALYSIS_MODULES.filter((m) =>
    m.label.toLowerCase().includes(q) ||
    m.tagline.toLowerCase().includes(q) ||
    m.description.toLowerCase().includes(q) ||
    m.tags?.some((t) => t.toLowerCase().includes(q)),
  );
}

/** Contagem de módulos por status (para o header do Atlas). */
export function moduleStats() {
  const available = ANALYSIS_MODULES.filter((m) => m.status === "available").length;
  const planned = ANALYSIS_MODULES.filter((m) => m.status === "planned").length;
  return { total: ANALYSIS_MODULES.length, available, planned };
}
