import type { AuditSource } from "../auditModel";

/**
 * Auditoria maximalista — SERP MULTI-ENGINE.
 *
 * Base: docs/fontes/serp-multi-engine-2026-08-25.md, server/routes/uniSerp.ts,
 * notebooks serp-fonte/serp-output e as docs públicas dos motores
 * (Google CSE, Brave Search API, Bing, DuckDuckGo HTML).
 */
export const SERP_AUDIT: AuditSource = {
  id: "serp",
  order: 3,
  name: "SERP multi-engine",
  category: "Presença web",
  status: "audited",
  implemented: true,
  sourceId: "serp",
  summary:
    "Busca web em múltiplos motores com ranking posicional unificado: Bing (scraping HTML público, sem chave), DuckDuckGo (HTML, sem chave mas rate-limita datacenters), Brave (API oficial com chave) e Google (Custom Search API com chave+CX). É a fonte de presença web — quem fala do app/tema e em que posição. Merge multi-engine com dedup por URL (melhor rank vence) e score derivado da posição (100 − rank).",
  endpoints: [
    {
      label: "Bing (scraping HTML)",
      url: "https://www.bing.com/search?q={q}&count={n}&cc={region}",
      method: "GET",
      auth: "nenhuma",
      notes: "Sem chave. Links embrulhados em bing.com/ck/a?u=a1<base64url> — a rota decodifica para a URL real.",
      status: "implemented",
    },
    {
      label: "DuckDuckGo HTML",
      url: "https://html.duckduckgo.com/html/?q={q}&kl={region}",
      method: "GET/POST",
      auth: "nenhuma",
      notes: "Rate-limita IPs de datacenter; falhas viram aviso honesto.",
      status: "implemented",
    },
    {
      label: "Brave Search API",
      url: "https://api.search.brave.com/res/v1/web/search?q={q}&count={n}&country={region}",
      method: "GET",
      auth: "BRAVE_API_KEY (header X-Subscription-Token)",
      notes: "API oficial; free tier ~2.000 consultas/mês.",
      status: "implemented",
    },
    {
      label: "Google Custom Search API",
      url: "https://www.googleapis.com/customsearch/v1?key={key}&cx={cx}&q={q}&gl={region}&lr=lang_{lang}",
      method: "GET",
      auth: "GOOGLE_API_KEY + GOOGLE_CX",
      notes: "100 consultas/dia grátis; paginação start/num (10/página, até 100 resultados).",
      status: "implemented",
    },
    {
      label: "SerpAPI (Bing/Google/50+ motores)",
      url: "https://serpapi.com/search?engine={engine}&q={q}",
      method: "GET",
      auth: "SERPAPI_KEY",
      notes: "Usada no notebook original (bing + bing_news); no sistema atual o Bing é scrape direto sem chave.",
      status: "available",
    },
    {
      label: "Serper.dev (Google Search API)",
      url: "https://google.serper.dev/search",
      method: "POST",
      auth: "SERPER_API_KEY",
      notes: "Caminho de menor custo para Google SERP sem CX (referenciado em SOURCE_FIELDS).",
      status: "available",
    },
    {
      label: "Rota do sistema uni-serp",
      url: "POST /functions/v1/uni-serp {action: search|content, query, engines[], region, lang, limit}",
      method: "POST",
      auth: "nenhuma (servidor local)",
      notes: "Motores em paralelo com disponibilidade honesta; ação content extrai a página de um resultado.",
      status: "implemented",
    },
  ],
  parameters: [
    { name: "query", type: "string", description: "Termo de busca (obrigatório).", status: "implemented" },
    { name: "engines", type: "enum[]", description: "Motores em multi-seleção; indisponíveis (sem chave) são reportados sem derrubar a coleta.", options: ["bing", "duckduckgo", "brave", "google"], default: "todos disponíveis", status: "implemented" },
    { name: "region (gl/cc/country/kl)", type: "string", description: "País da busca — cada motor tem seu parâmetro (gl no Google, cc no Bing, country na Brave, kl no DDG).", default: "br", status: "implemented" },
    { name: "lang (lr/search_lang)", type: "string", description: "Idioma dos resultados (lr=lang_pt no Google; search_lang na Brave).", default: "pt", status: "implemented" },
    { name: "limit", type: "number", description: "Máximo de resultados por motor (1ª página).", default: "10", status: "implemented" },
    { name: "start/num (paginação)", type: "number", description: "Google CSE pagina de 10 em 10 até 100 resultados — hoje só a 1ª página.", status: "available" },
    { name: "searchType=image", type: "enum", description: "Google CSE também busca imagens (mesma cota).", options: ["(vazio)=web", "image"], status: "available" },
    { name: "dateRestrict", type: "string", description: "Google CSE: restringe por data (d1/w1/m1/y1…).", status: "available" },
    { name: "freshness", type: "enum", description: "Brave: janela de recência (pd=past day, pw, pm, py).", options: ["pd", "pw", "pm", "py"], status: "available" },
    { name: "siteSearch / fileType / exactTerms", type: "string", description: "Operadores estruturados do Google CSE (sem precisar colar no query).", status: "available" },
    { name: "safe", type: "enum", description: "SafeSearch (off/moderate/strict) — Bing, Brave e Google expõem.", options: ["off", "moderate", "strict"], status: "available" },
    { name: "tbs=qdr:* (URL pública)", type: "string", description: "Filtro temporal da URL pública do Google (qdr:h/d/w/m/y).", status: "implemented" },
    { name: "tbm (verticais da URL pública)", type: "enum", description: "Tipo de busca: nws/vid/isch/shop/lcl.", options: ["nws", "vid", "isch", "shop", "lcl"], status: "available" },
    { name: "udm (novas vistas da URL pública)", type: "enum", description: "Substituto do tbm: 2=imagens, 14=web sem AI, 39=vídeos curtos, 50=AI Mode.", options: ["2", "14", "39", "50"], status: "available" },
    { name: "filter=0 (decluster)", type: "bitfield", description: "Desativa o agrupamento de resultados de mesmo domínio (URL pública).", status: "implemented" },
    { name: "pws=0 (sem personalização)", type: "bitfield", description: "Resultados limpos sem sinais do usuário (URL pública).", status: "implemented" },
    { name: "nfpr=1 (sem autocorreção)", type: "bitfield", description: "Desativa o rewrite do termo (URL pública).", status: "implemented" },
    { name: "uule (geo cliente)", type: "string", description: "Localização geográfica cifrada do usuário (URL pública).", status: "available" },
  ],
  capabilities: [
    { label: "Busca web em 4 motores com rank posicional unificado", status: "implemented" },
    { label: "Merge multi-engine com dedup por URL (melhor rank vence)", status: "implemented" },
    { label: "Disponibilidade honesta por motor (sem chave → aviso, nunca falha total)", status: "implemented" },
    { label: "Extração de conteúdo da página de um resultado (ação content → fonte web)", status: "implemented" },
    { label: "Score derivado do rank (posição 1 = 99)", status: "implemented" },
    { label: "Decodificação dos links embrulhados do Bing (ck/a base64url)", status: "implemented" },
    { label: "Paginação profunda (Google CSE até 100; Brave offset; Bing first=)", status: "available" },
    { label: "Busca de imagens (Google CSE searchType; Brave /images)", status: "available" },
    { label: "Bing News via SerpAPI (fallback usado no notebook)", status: "available" },
    { label: "Rank tracking agendado (posição de marca/concorrentes ao longo do tempo)", status: "available" },
    { label: "Extração de conteúdo em lote do top-N", status: "available" },
  ],
  combinations: [
    "query × 4 motores — cobertura e consenso (mesmo link em N motores = autoridade)",
    "query × região × idioma — presença web muda por mercado",
    "query × data (dateRestrict/freshness) — cobertura recente vs histórica",
    "SERP × fonte web (content) — do resultado ao texto completo da página",
    "SERP × Suggest — os termos descobertos no autocomplete viram queries de presença",
  ],
  outputs: [
    { name: "title", type: "string", description: "Título do resultado.", presence: "always", status: "implemented" },
    { name: "url", type: "string", description: "URL real (decodificada no Bing).", presence: "always", status: "implemented" },
    { name: "snippet (text)", type: "string", description: "Trecho/descrição do resultado.", presence: "common", status: "implemented", reliability: "DDG/Bing às vezes omitem" },
    { name: "engine", type: "enum", description: "Motor de origem (bing/duckduckgo/brave/google).", presence: "always", status: "implemented" },
    { name: "rank", type: "number", description: "Posição no motor — base do score comparável.", presence: "always", status: "implemented" },
    { name: "displayLink / formattedUrl", type: "string", description: "Domínio de exibição e URL formatada (Google CSE).", presence: "common", status: "available" },
    { name: "pagemap (metatags, cse_image, sitelinks)", type: "objeto", description: "Google CSE devolve pagemap rico (og:image, breadcrumbs, ratings schema.org).", presence: "common", status: "available" },
    { name: "published/paginação enriquecida", type: "string", description: "Brave devolve age/data do resultado; clusters e rich snippets.", presence: "common", status: "available" },
    { name: "conteúdo da página (ação content)", type: "texto", description: "Texto extraído da página do resultado (readability) — ponte com a fonte web.", presence: "conditional", status: "implemented" },
  ],
  derivations: [
    "Consenso multi-motor: URLs presentes em N motores (autoridade real)",
    "Share de voz por domínio (quem domina o termo)",
    "Detecção de concorrentes orgânicos (domínios recorrentes)",
    "Rank tracking temporal (snapshots agendados)",
    "Corpus de páginas para a fonte web (content em lote)",
  ],
  limits: [
    "1ª página por motor hoje (~10 resultados cada)",
    "Google CSE: 100 consultas/dia grátis, máx 100 resultados por query",
    "Brave free tier: ~2.000 consultas/mês",
    "DuckDuckGo rate-limita datacenters (HTML)",
    "Scraping de Bing/DDG é frágil a mudanças de markup (parsing defensivo)",
  ],
  reliability: {
    consistency:
      "Alta por consulta no curto prazo; rankings mudam com o tempo (é a natureza da SERP) — snapshots temporais são o uso correto.",
    stability:
      "APIs oficiais (Brave, Google CSE) são estáveis; scraping (Bing/DDG) quebra com mudança de markup — parse defensivo mitiga.",
    risks: [
      "Sem chaves: só Bing/DDG funcionam (Google/Brave indisponíveis)",
      "Rate-limit do DDG em datacenter",
      "Bloqueio de scraping por fingerprint de bot",
    ],
    fallbacks: [
      "Motores indisponíveis são reportados honestamente — a coleta nunca falha inteira",
      "Decodificação defensiva dos links do Bing",
      "Serper.dev/SerpAPI como motores alternativos de Google com chave",
    ],
  },
  references: [
    { label: "Doc da fonte no sistema", url: "docs/fontes/serp-multi-engine-2026-08-25.md" },
    { label: "Notebook de testes (serp-fonte)", url: "docs/fontes/notebooks/serp-fonte.md" },
    { label: "Saídas de exemplo (serp-output)", url: "docs/fontes/notebooks/serp-output.md" },
    { label: "Google Custom Search API", url: "https://developers.google.com/custom-search/v1/reference/rest/v1/cse/list" },
    { label: "Brave Search API", url: "https://brave.com/search/api/" },
  ],
};
