import type { AuditSource } from "../auditModel";

/**
 * Auditoria maximalista — GOOGLE TRENDS.
 *
 * Base: docs/fontes/google-trends-2026-08-25.md, a investigação 2026-08-25
 * do AGENTS.md (RPC batchexecute i0OFE + RSS "Em alta"), notebooks
 * trends-fonte/trends-output, server/routes/uniTrends.ts,
 * server/lib/trendingCore.ts e a documentação pública do pytrends.
 */
export const TRENDS_AUDIT: AuditSource = {
  id: "trends",
  order: 2,
  name: "Google Trends",
  category: "Demanda",
  status: "audited",
  implemented: true,
  sourceId: "trends",
  summary:
    "O Google Trends mede demanda e sazonalidade em escala relativa 0–100. O sistema usa TRÊS superfícies da fonte: (1) a widget API não-oficial (explore → widgetdata: timeline, geo, queries relacionadas) para análise de termos; (2) o RPC interno i0OFE da página 'Em alta' (lista completa de trends com volume, crescimento, consultas relacionadas e topicIds); (3) o RSS 'Em alta' (top-10 com notícias/imagens, usado como enrichment). Scores são RELATIVOS ao pico da própria consulta — comparações só valem dentro da mesma execução.",
  endpoints: [
    {
      label: "Explore (fase 1 — widgets)",
      url: "https://trends.google.com/trends/api/explore",
      method: "POST",
      auth: "nenhuma",
      notes: "Devolve os tokens dos widgets (TIMESERIES/GEO_MAP/RELATED_QUERIES) por termo × geo × período × gprop.",
      status: "implemented",
    },
    {
      label: "Widget data (fase 2)",
      url: "https://trends.google.com/trends/api/widgetdata/{multiline|geomap|relatedsearches}?token=…&req=…",
      method: "GET",
      auth: "nenhuma",
      notes: "multiline = timeline; geomap = por região; relatedsearches = queries top/rising.",
      status: "implemented",
    },
    {
      label: "RPC 'Em alta' (trending now)",
      url: "https://trends.google.com/_/TrendsUi/data/batchexecute?rpcids=i0OFE",
      method: "POST",
      auth: "nenhuma",
      notes: "f.req=[[[\"i0OFE\",\"[null,null,\\\"BR\\\",0,null,24]\",null,\"generic\"]]] — args [?, ?, geo, 0, null, hours]. Lista COMPLETA (4h≈25 · 24h≈230 · 48h≈630 · 7d≈1.800 trends).",
      status: "implemented",
    },
    {
      label: "RSS 'Em alta'",
      url: "https://trends.google.com/trending/rss?geo=BR",
      method: "GET",
      auth: "nenhuma",
      notes: "Top-10 com ht:news_item (título/url/fonte/imagem). IGNORA hours/category/sort — sempre o mesmo top-10; usado só como enrichment.",
      status: "implemented",
    },
    {
      label: "Daily trends (legado)",
      url: "https://trends.google.com/trends/api/dailytrends?geo=BR",
      method: "GET",
      auth: "nenhuma",
      notes: "Morto (404) — substituído pelo RPC i0OFE.",
      status: "unavailable",
    },
    {
      label: "Rotas do sistema",
      url: "POST /functions/v1/uni-trends (explore) · POST /functions/v1/uni-trending (trending|gather)",
      method: "POST",
      auth: "nenhuma (servidor local)",
      notes: "Cache TTL 30min (explore) / 10min (trending) com parâmetros completos; gather une as 4 janelas com dedup e proveniência.",
      status: "implemented",
    },
  ],
  parameters: [
    { name: "terms", type: "string[]", description: "Até 5 termos comparados na mesma execução (share de interesse relativo).", range: "1–5", status: "implemented" },
    { name: "geo / region", type: "enum", description: "País (BR, US, '' = mundo). No trending: 18 regiões curadas; a API aceita qualquer geo.", options: ["BR", "US", "PT", "…", "'' (mundo)"], default: "BR", status: "implemented" },
    { name: "hl (lang)", type: "string", description: "Idioma da interface/resposta (pt-BR, en-US…).", default: "pt-BR", status: "implemented" },
    {
      name: "timeframe",
      type: "enum",
      description: "Período da série. Sistema oferece 6 presets; a API aceita também janelas de horas (now 1-H/4-H/1-d) e range custom (start end).",
      options: ["now 1-H", "now 4-H", "now 1-d", "now 7-d", "today 1-m", "today 3-m", "today 12-m", "today 5-y", "all (2004→)", "custom YYYY-MM-DD YYYY-MM-DD"],
      default: "today 3-m",
      status: "partial",
    },
    { name: "gprop", type: "enum", description: "Propriedade Google (vertical).", options: ["'' (web)", "images", "news", "youtube", "froogle (shopping)"], default: "'' (web)", status: "implemented" },
    { name: "category", type: "number", description: "Categoria da taxonomia Trends (0 = todas). Hoje fixo em 0 — as ~1.400 categorias não são exploradas.", default: "0", status: "available" },
    { name: "resolution", type: "enum", description: "Granularidade do geo map: COUNTRY, REGION (estado), CITY, DMA.", options: ["COUNTRY", "REGION", "CITY", "DMA"], default: "COUNTRY", status: "available" },
    { name: "inc_low_vol", type: "boolean", description: "Inclui regiões de baixo volume no geo map (evita mapa vazio).", default: "false", status: "available" },
    { name: "hours (trending)", type: "enum", description: "Janela do 'Em alta': 4h, 24h, 48h, 168h (7d). Rendimento muito diferente por janela.", options: ["4", "24", "48", "168"], default: "24", status: "implemented" },
    { name: "topn", type: "number", description: "Máximo de regiões/queries por visão (teto 25).", range: "1–25", default: "12", status: "implemented" },
    { name: "tz", type: "number", description: "Timezone em minutos (pytrends usa tz=0/UTC); afeta o alinhamento dos pontos da timeline.", default: "0", status: "available" },
  ],
  capabilities: [
    { label: "Timeline de interesse (TIMESERIES, escala 0–100)", status: "implemented" },
    { label: "Interesse por região (GEO_MAP, até 25 regiões)", status: "implemented" },
    { label: "Queries relacionadas top + rising (RELATED_QUERIES)", status: "implemented" },
    { label: "Comparação de até 5 termos por execução", status: "implemented" },
    { label: "Trending 'Em alta' completo por janela (4h/24h/48h/7d) com volume e crescimento %", status: "implemented" },
    { label: "Enrichment RSS: notícias vinculadas (título/url/fonte/imagem) no top-10", status: "implemented" },
    { label: "Gather multi-janela com dedup e proveniência (em quais janelas apareceu)", status: "implemented" },
    { label: "Tópicos relacionados top + rising (widget RELATED_TOPICS)", status: "available", notes: "O widget existe no explore; o sistema não o consome." },
    { label: "Categorias da taxonomia (category ≠ 0)", status: "available" },
    { label: "Granularidade sub-país (REGION/CITY/DMA)", status: "available" },
    { label: "Sugestões de entidade/keyword (endpoint suggestions do pytrends)", status: "available" },
    { label: "Flag isPartial da timeline (ponto final incompleto)", status: "implemented", notes: "O Google marca o último ponto como parcial; exibido na /auditoria." },
    { label: "Stitching de janelas para série diária longa", status: "available", notes: "A API reduz granularidade em períodos longos; sobrepor janelas com normalização resolve." },
    { label: "Alertas de rising queries agendados", status: "available" },
    { label: "Multirange Interest Over Time (comparação de períodos diferentes)", status: "available" },
    { label: "Historical Hourly Interest (série horária histórica por semana)", status: "available" },
    { label: "Top Charts anual (categorias oficiais)", status: "available" },
    { label: "Realtime Search Trends (minuto a minuto)", status: "available" },
  ],
  combinations: [
    "até 5 termos × 6 períodos × 5 verticais (gprop) — 30 combos possíveis por conjunto de termos",
    "trending: 18 regiões × 4 janelas = 72 coletas de 'Em alta' por varredura completa",
    "multi-seleção de períodos × verticais com teto de 12 combos por execução (rate-limit)",
    "termo × geo × hl — a mesma query muda por país e idioma",
    "trending × RSS enrichment — ranking interno + notícias do top-10",
  ],
  outputs: [
    { name: "timeline: date", type: "string", description: "Ponto temporal da série (dia/semana/mês conforme o período).", presence: "always", status: "implemented" },
    { name: "timeline: value (0–100)", type: "number", description: "Interesse relativo — normalizado pelo pico da PRÓPRIA consulta.", presence: "always", status: "implemented", reliability: "relativo: só comparável dentro da mesma execução" },
    { name: "timeline: isPartial", type: "boolean", description: "O último ponto cobre um período incompleto (semana/mês corrente).", presence: "common", status: "available" },
    { name: "geo: region + value", type: "string + number", description: "Região geográfica e interesse 0–100.", presence: "always", status: "implemented" },
    { name: "related: query + value", type: "string + number|string", description: "Queries relacionadas top (0–100) e rising (% de crescimento; 'Breakout' = >5000%).", presence: "always", status: "implemented" },
    { name: "related topics: title + type + value", type: "misto", description: "Tópicos da taxonomia Google relacionados (top/rising).", presence: "common", status: "available" },
    { name: "trending: title", type: "string", description: "O termo/entidade em alta.", presence: "always", status: "implemented" },
    { name: "trending: volume", type: "number", description: "Volume estimado de buscas na janela.", presence: "always", status: "implemented" },
    { name: "trending: growthPct", type: "number", description: "Crescimento % na janela.", presence: "always", status: "implemented" },
    { name: "trending: startedAt/endedAt", type: "timestamp", description: "Início (e fim, quando encerrado) da trend.", presence: "always", status: "implemented" },
    { name: "trending: relatedQueries", type: "string[]", description: "Consultas relacionadas à trend.", presence: "always", status: "implemented" },
    { name: "trending: topicIds / entityIds", type: "number[]", description: "Taxonomia interna do Google por trend (filtro client-side, como a página oficial).", presence: "common", status: "implemented" },
    { name: "rss: notícias (título/url/fonte/imagem)", type: "objeto", description: "ht:news_item por trend do top-10.", presence: "conditional", status: "implemented", reliability: "só o top-10 do RSS traz notícias" },
  ],
  derivations: [
    "Sazonalidade e tendência (subida/queda) por regressão sobre a timeline",
    "Share de interesse entre concorrentes (mesma execução)",
    "Rising = detector de oportunidade ('Breakout' sinaliza explosão)",
    "Correlação trends × reviews do dataset (cruzamento temporal)",
    "Taxonomia de tópicos por trend (topicIds → labels)",
    "Mapa de calor regional (geo × valor)",
  ],
  limits: [
    "429 por IP é o limitador prático — retries com backoff e cache de 30min (explore) / 10min (trending)",
    "Granularidade da timeline depende do período: diária ≤ ~9 meses; semanal/mensal acima",
    "Scores 0–100 relativos ao pico da própria consulta — nunca comparar execuções diferentes",
    "Widget API não oficial: shape pode mudar sem aviso",
    "RSS ignora hours/category/sort (sempre o mesmo top-10)",
    "Teto de 12 combos por execução na multi-seleção (orçamento explícito)",
  ],
  reliability: {
    consistency:
      "Alta para a mesma configuração (cache de 30min torna leituras idênticas); scores são relativos e estáveis dentro da execução.",
    stability:
      "Widget API não oficial mas estável há anos; o endpoint legado dailytrends morreu (404) — o sistema já migrou para o RPC i0OFE.",
    risks: [
      "Rate-limit 429 por IP em coletas massivas",
      "Mudança de shape do batchexecute (RPC interno sem contrato)",
      "Trends de baixo volume retornam séries zeradas/esparsas",
    ],
    fallbacks: [
      "Cache TTL evita re-bater na API em falhas transitórias",
      "Retry com backoff no 429",
      "RSS como enrichment opcional — falha dele não invalida o RPC",
      "Gather devolve resultado parcial com proveniência quando uma janela falha",
    ],
  },
  references: [
    { label: "Doc da fonte no sistema", url: "docs/fontes/google-trends-2026-08-25.md" },
    { label: "Notebook de testes (trends-fonte)", url: "docs/fontes/notebooks/trends-fonte.md" },
    { label: "Saídas de exemplo (trends-output)", url: "docs/fontes/notebooks/trends-output.md" },
    { label: "Página /trending (Em alta)", url: "/trending" },
    { label: "pytrends (referência da widget API)", url: "https://github.com/GeneralMills/pytrends" },
  ],
};
