/**
 * Source Registry — catálogo de fontes com capabilities (Phase 3 do
 * target-state; briefing §13/§14).
 *
 * Foundation da expansão multi-fonte: metadados declarativos por fonte, sem
 * nenhum acoplamento a comportamento. As 2 fontes ativas (apple, google)
 * declaram suas capacidades; as rotas específicas existentes permanecem as
 * implementações ativas — este catálogo é o ponto de verdade para UI,
 * capability matrix e futura rota genérica.
 *
 * Prioridade de método declarada por fonte (briefing §14):
 * API oficial → export/feed oficial → endpoint público documentado →
 * browser → scraping. Limitações de ToS/rate-limit registradas em `tosNote`.
 */

export interface SourceCapabilities {
  search?: boolean;
  lookup?: boolean;
  reviews?: boolean;
  topCharts?: boolean;
  healthCheck?: boolean;
}

export type SourceKind = "store" | "social" | "news" | "search" | "academic" | "developer" | "video";

export interface SourceMeta {
  id: string;
  label: string;
  kind: SourceKind;
  auth: "none" | "apikey" | "oauth";
  capabilities: SourceCapabilities;
  rateLimit?: { rps: number; burst?: number };
  supportsIncremental?: boolean;
  supportsHistorical?: boolean;
  regions?: string[];
  tosNote?: string;
  collector?: string;
  collectorVersion?: string;
  method?: string; // caminho preferido (ex.: "api+ssr", "npm google-play-scraper")
}

const SOURCES: SourceMeta[] = [
  {
    id: "apple",
    label: "Apple App Store",
    kind: "store",
    auth: "none",
    capabilities: { search: true, lookup: true, reviews: true, topCharts: true },
    rateLimit: { rps: 1 }, // amp-api rate-limita por IP agressivamente (429)
    supportsIncremental: true,
    supportsHistorical: false,
    regions: ["br", "us", "gb", "pt", "ca", "au", "de", "fr", "it", "es", "jp"],
    tosNote: "amp-api + SSR + RSS via proxies públicos; renderização web pública. Sem auth.",
    collector: "apple-reviews",
    collectorVersion: "1",
    method: "amp-api + SSR web + RSS fallback (3 fontes combinadas)",
  },
  {
    id: "google",
    label: "Google Play",
    kind: "store",
    auth: "none",
    capabilities: { search: true, lookup: true, reviews: true, topCharts: true, healthCheck: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["br", "us"],
    tosNote: "Pacote npm google-play-scraper (renderização pública da loja JSON). Sem auth.",
    collector: "google-play-scraper",
    collectorVersion: "1",
    method: "npm google-play-scraper (multi-sort dedupe)",
  },
  // Primeira fonte além das lojas: enciclopédia pública (discovery+article).
  {
    id: "wikipedia",
    label: "Wikipedia",
    kind: "academic",
    auth: "none",
    capabilities: { search: true, lookup: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["pt", "en", "es", "fr", "de", "it"],
    tosNote:
      "MediaWiki Action API pública (termos.legal/wikimedia). Aliases para outbound sem auth; respeitamos rate-limits da wiki.",
    collector: "wikipedia",
    collectorVersion: "1",
    method: "Wikimedia API (action=query list=search / prop=extracts)",
  },
  {
    id: "hackernews",
    label: "Hacker News",
    kind: "social",
    auth: "none",
    capabilities: { search: true, lookup: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["us", "global"],
    tosNote: "API Algolia oficial do HN (hn.algolia.com), pública e documentada. Uso moderado.",
    collector: "uni-hn",
    collectorVersion: "1",
    method: "Algolia HN API (search/search_by_date + items/{id})",
  },
  {
    id: "gdelt",
    label: "GDELT",
    kind: "news",
    auth: "none",
    capabilities: { search: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["global", "br", "us"],
    tosNote: "GDELT Project API v2 (api.gdeltproject.org), pública e aberta. Uso moderado.",
    collector: "uni-gdelt",
    collectorVersion: "1",
    method: "GDELT DOC 2.0 API (artlist JSON, sourceLang/date range)",
  },
  {
    id: "arxiv",
    label: "arXiv",
    kind: "academic",
    auth: "none",
    capabilities: { search: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["global"],
    tosNote: "arXiv API pública (export.arxiv.org), Atom XML. Uso moderado.",
    collector: "uni-arxiv",
    collectorVersion: "1",
    method: "arXiv API (search_query=all:, sortBy relevance/date)",
  },
  {
    id: "stackexchange",
    label: "StackExchange",
    kind: "developer",
    auth: "none",
    capabilities: { search: true, lookup: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["global", "br"],
    tosNote: "StackExchange API 2.3 pública (quota 300 req/dia por IP, sem key). Uso moderado.",
    collector: "uni-stackexchange",
    collectorVersion: "1",
    method: "API 2.3 (search/advanced + questions/{id}/answers)",
  },
  {
    id: "github",
    label: "GitHub",
    kind: "developer",
    auth: "none",
    capabilities: { search: true },
    supportsIncremental: true,
    supportsHistorical: false,
    regions: ["global"],
    tosNote: "GitHub Search API. Sem token: 10 req/min; com GITHUB_TOKEN no servidor: 30 req/min.",
    collector: "uni-github",
    collectorVersion: "1",
    method: "GitHub Search API (repositories/issues)",
  },
  {
    id: "semanticscholar",
    label: "Semantic Scholar",
    kind: "academic",
    auth: "none",
    capabilities: { search: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["global"],
    tosNote: "Semantic Scholar Graph API pública (rate-limit apertado; backoff exponencial).",
    collector: "uni-semanticscholar",
    collectorVersion: "1",
    method: "Graph v1 paper/search (citationCount, abstract)",
  },
  {
    id: "steam",
    label: "Steam",
    kind: "store",
    auth: "none",
    capabilities: { search: true, lookup: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["global", "br"],
    tosNote: "Steam Store endpoints públicos (search HTML + appreviews JSON). Uso moderado.",
    collector: "uni-steam",
    collectorVersion: "1",
    method: "Store search (scrape) + appreviews JSON (idioma/votos/playtime)",
  },
  {
    id: "reclameaqui",
    label: "ReclameAqui",
    kind: "social",
    auth: "none",
    capabilities: { search: true, lookup: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["br"],
    tosNote: "Endpoints JSON internos do webapp RA (iosearch/iosite raichu). Cloudflare bloqueia IPs de datacenter — funciona de rede residencial. Uso moderado.",
    collector: "uni-reclameaqui",
    collectorVersion: "1",
    method: "companies/search + query/companyComplains + query/{termo} (status derivado como o web client)",
  },
  {
    id: "producthunt",
    label: "Product Hunt",
    kind: "social",
    auth: "none",
    capabilities: { search: false, lookup: true },
    supportsIncremental: true,
    supportsHistorical: false,
    regions: ["global"],
    tosNote: "Feed Atom público (sem auth). GraphQL oficial v2 exige PRODUCT_HUNT_TOKEN (developer token). Uso moderado; cache 30min.",
    collector: "uni-producthunt",
    collectorVersion: "1",
    method: "feed Atom público (/feed, parse RSS/Atom) + GraphQL v2 opcional (votos/tópicos/comentários)",
  },
  {
    id: "web",
    label: "Web (qualquer URL/PDF)",
    kind: "search",
    auth: "none",
    capabilities: { lookup: true },
    supportsIncremental: false,
    supportsHistorical: true,
    regions: ["global"],
    tosNote: "Coleta de páginas públicas fornecidas pelo usuário. Respeitar robots/ToS do site de origem.",
    collector: "uni-web",
    collectorVersion: "1",
    method: "Fetch + extração de texto (Readability-like) / unpdf",
  },
  {
    id: "feed",
    label: "RSS/Atom (qualquer feed)",
    kind: "news",
    auth: "none",
    capabilities: { search: false, lookup: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["global"],
    tosNote: "Feeds RSS/Atom públicos fornecidos pelo usuário.",
    collector: "uni-web",
    collectorVersion: "1",
    method: "Parser genérico RSS 2.0/Atom (cheerio xmlMode)",
  },
  {
    id: "devto",
    label: "DEV Community",
    kind: "social",
    auth: "none",
    capabilities: { search: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["global"],
    tosNote: "API Forem pública (dev.to/api/articles?tag=).",
    collector: "uni-source",
    collectorVersion: "1",
    method: "artigos por tag com reações/comentários",
  },
  {
    id: "lobsters",
    label: "Lobsters",
    kind: "social",
    auth: "none",
    capabilities: { search: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["global"],
    tosNote: "JSON público (search.json).",
    collector: "uni-source",
    collectorVersion: "1",
    method: "stories com score/comentários",
  },
  {
    id: "mastodon",
    label: "Mastodon",
    kind: "social",
    auth: "none",
    capabilities: { search: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["global"],
    tosNote: "Timeline pública de hashtag (mastodon.social).",
    collector: "uni-source",
    collectorVersion: "1",
    method: "posts por hashtag com favs/boosts",
  },
  {
    id: "bluesky",
    label: "Bluesky",
    kind: "social",
    auth: "none",
    capabilities: { search: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["global"],
    tosNote: "AT Protocol público (public.api.bsky.app searchPosts).",
    collector: "uni-source",
    collectorVersion: "1",
    method: "busca de posts com likes/reposts",
  },
  {
    id: "wikidata",
    label: "Wikidata",
    kind: "search",
    auth: "none",
    capabilities: { search: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["global"],
    tosNote: "wbsearchentities (Wikimedia API).",
    collector: "uni-source",
    collectorVersion: "1",
    method: "entidades estruturadas com descrição",
  },
  {
    id: "openalex",
    label: "OpenAlex",
    kind: "academic",
    auth: "none",
    capabilities: { search: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["global"],
    tosNote: "OpenAlex API sem key (works?search=).",
    collector: "uni-source",
    collectorVersion: "1",
    method: "papers com citações/OA",
  },
  {
    id: "crossref",
    label: "Crossref",
    kind: "academic",
    auth: "none",
    capabilities: { search: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["global"],
    tosNote: "Crossref REST sem key (works?query=).",
    collector: "uni-source",
    collectorVersion: "1",
    method: "metadados DOI com citações",
  },
  {
    id: "openlibrary",
    label: "Open Library",
    kind: "store",
    auth: "none",
    capabilities: { search: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["global"],
    tosNote: "Open Library search.json sem key.",
    collector: "uni-source",
    collectorVersion: "1",
    method: "livros com notas/autores",
  },
  {
    id: "npm",
    label: "npm",
    kind: "developer",
    auth: "none",
    capabilities: { search: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["global"],
    tosNote: "registry.npmjs.org/-/v1/search.",
    collector: "uni-source",
    collectorVersion: "1",
    method: "pacotes JS com score de busca",
  },
  {
    id: "pypi",
    label: "PyPI",
    kind: "developer",
    auth: "none",
    capabilities: { lookup: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["global"],
    tosNote: "pypi.org/pypi/<nome>/json (lookup exato).",
    collector: "uni-source",
    collectorVersion: "1",
    method: "pacote Python por nome",
  },
  {
    id: "rubygems",
    label: "RubyGems",
    kind: "developer",
    auth: "none",
    capabilities: { search: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["global"],
    tosNote: "rubygems.org/api/v1/search.json público.",
    collector: "uni-source",
    collectorVersion: "1",
    method: "gems com downloads",
  },
  {
    id: "cratesio",
    label: "Crates.io",
    kind: "developer",
    auth: "none",
    capabilities: { search: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["global"],
    tosNote: "crates.io/api/v1/crates público (UA identificada).",
    collector: "uni-source",
    collectorVersion: "1",
    method: "crates com downloads/repositório",
  },
  {
    id: "doaj",
    label: "DOAJ",
    kind: "academic",
    auth: "none",
    capabilities: { search: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["global"],
    tosNote: "doaj.org/api open access público.",
    collector: "uni-source",
    collectorVersion: "1",
    method: "artigos open access com DOI",
  },
  {
    id: "openfoodfacts",
    label: "Open Food Facts",
    kind: "store",
    auth: "none",
    capabilities: { search: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["global"],
    tosNote: "Open Food Facts open data (ODbL); search.pl público.",
    collector: "uni-source",
    collectorVersion: "1",
    method: "produtos com nutri-score",
  },
  {
    id: "archive",
    label: "Internet Archive",
    kind: "search",
    auth: "none",
    capabilities: { search: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["global"],
    tosNote: "archive.org advancedsearch.php público.",
    collector: "uni-source",
    collectorVersion: "1",
    method: "mídia arquivada com downloads",
  },
  {
    id: "tvmaze",
    label: "TVMaze",
    kind: "video",
    auth: "none",
    capabilities: { search: true },
    supportsIncremental: true,
    supportsHistorical: false,
    regions: ["global"],
    tosNote: "api.tvmaze.com/search/shows público.",
    collector: "uni-source",
    collectorVersion: "1",
    method: "séries com nota/gêneros",
  },
  {
    id: "itchio",
    label: "itch.io",
    kind: "store",
    auth: "none",
    capabilities: { search: true },
    supportsIncremental: true,
    supportsHistorical: false,
    regions: ["global"],
    tosNote: "Scrape da página de busca pública da itch.io (search?q=). Sem API oficial.",
    collector: "uni-source",
    collectorVersion: "1",
    method: "busca HTML de jogos indie",
  },
  // Fontes Uni (página /00) — demanda e descoberta.
  {
    id: "suggest",
    label: "Google Suggest",
    kind: "search",
    auth: "none",
    capabilities: { search: true },
    supportsIncremental: true,
    supportsHistorical: false,
    regions: ["br", "us", "gb", "pt", "es", "fr", "de", "it", "jp"],
    tosNote: "Endpoint público de autocomplete (suggestqueries.google.com). Uso moderado; expansão alfabética em lotes.",
    collector: "uni-suggest",
    collectorVersion: "1",
    method: "Google Suggest API (client=chrome, ds por vertical) + expansão a-z/0-9",
  },
  {
    id: "trends",
    label: "Google Trends",
    kind: "search",
    auth: "none",
    capabilities: { search: true },
    supportsIncremental: true,
    supportsHistorical: true,
    regions: ["BR", "US", "GB", "PT", "ES", "FR", "DE", "IT", "JP"],
    tosNote: "Endpoints públicos não-oficiais do Google Trends (mesmo fluxo do pytrends). Rate-limit moderado; evitar polling agressivo.",
    collector: "uni-trends",
    collectorVersion: "1",
    method: "explore → widgetdata (multiline/comparedgeo/relatedsearches)",
  },
  {
    id: "serp",
    label: "SERP (Bing/DDG/Brave/Google)",
    kind: "search",
    auth: "none",
    capabilities: { search: true, lookup: true },
    supportsIncremental: true,
    supportsHistorical: false,
    regions: ["br", "us", "gb", "pt", "es", "fr", "de", "it", "jp"],
    tosNote: "Bing via HTML público; DuckDuckGo rate-limita datacenters (erro honesto); Brave/Google CSE exigem API key no env do servidor.",
    collector: "uni-serp",
    collectorVersion: "1",
    method: "scraping HTML (bing/ddg) + APIs oficiais quando key presente (brave/google-cse)",
  },
  {
    id: "youtube",
    label: "YouTube",
    kind: "video",
    auth: "none",
    capabilities: { search: true, reviews: true },
    supportsIncremental: true,
    supportsHistorical: false,
    tosNote: "Scraping público (ytInitialData + youtubei continuation), sem API key. Comentários = top comentários (ordenação padrão do YT).",
    collector: "uni-youtube",
    collectorVersion: "1",
    method: "scraping /results (videos) + /watch + youtubei/v1/next (comments)",
  },
  {
    id: "reddit",
    label: "Reddit",
    kind: "social",
    auth: "apikey",
    capabilities: { search: true, reviews: true },
    supportsIncremental: true,
    supportsHistorical: false,
    tosNote: "JSON público funciona de IPs residenciais; datacenters são bloqueados (403). OAuth client_credentials (REDDIT_CLIENT_ID/SECRET no env) é o caminho robusto.",
    collector: "uni-reddit",
    collectorVersion: "1",
    method: "oauth.reddit.com (client_credentials) com fallback para JSON público *.json",
  },
];

/** Catálogo completo de fontes (metadados declarativos). */
export function listSources(): SourceMeta[] {
  return SOURCES;
}

/** Lookup por id (`apple`/`google`/…). Undefined para ids desconhecidos. */
export function getSource(id: string | undefined): SourceMeta | undefined {
  return SOURCES.find((s) => s.id === id);
}

/** Verdadeiro se a fonte suporta a capability dada. */
export function hasCapability(id: string, cap: keyof SourceCapabilities): boolean {
  const src = getSource(id);
  return !!src?.capabilities?.[cap];
}
